import { useCallback, useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/lib/auth'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Loader2, Clock } from 'lucide-react'

type Session={id:string;user_id:string;company_id:string;started_at:string;ended_at:string|null;type:string;source:string;qr_code_id:string|null;location:unknown}
type Person={id:string;username:string;full_name:string}
export default function UserAttendanceTab(){
 const{user}=useAuth();const[rows,setRows]=useState<Array<Session&{person:Person|null}>>([]);const[loading,setLoading]=useState(true)
 const load=useCallback(async()=>{if(!user?.company_id){setLoading(false);return}setLoading(true);try{const{data,error}=await supabase.from('attendance_sessions').select('id,user_id,company_id,started_at,ended_at,type,source,qr_code_id,location').eq('company_id',user.company_id).order('started_at',{ascending:false}).limit(250);if(error)throw error;const ids=[...new Set((data??[]).map(s=>s.user_id))];const{data:profiles}=ids.length?await supabase.from('profiles').select('id,username,full_name').in('id',ids):{data:[],error:null};const map=new Map((profiles??[]).map(p=>[p.id,p as Person]));setRows((data??[]).map(s=>({...s,person:map.get(s.user_id)??null}))) }finally{setLoading(false)}},[user?.company_id])
 useEffect(()=>{void load();if(!user?.company_id)return;const c=supabase.channel(`attendance-sessions:${user.company_id}`).on('postgres_changes',{event:'*',schema:'public',table:'attendance_sessions',filter:`company_id=eq.${user.company_id}`},()=>void load()).subscribe();return()=>{void supabase.removeChannel(c)}},[load,user?.company_id])
 const duration=(s:Session)=>((new Date(s.ended_at??new Date().toISOString()).getTime()-new Date(s.started_at).getTime())/3600000);const total=rows.reduce((n,s)=>n+(s.type==='work'?duration(s):0),0)
 return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2"><Card className="p-5"><p className="text-sm text-muted-foreground">Session records</p><p className="mt-1 text-2xl font-semibold">{rows.length}</p></Card><Card className="p-5"><p className="text-sm text-muted-foreground">Work hours in loaded records</p><p className="mt-1 text-2xl font-semibold">{total.toFixed(1)}h</p></Card></div><Card className="overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Attendance sessions</h2><p className="mt-1 text-sm text-muted-foreground">Attendance is derived from individual work and break sessions.</p></div>{loading?<div className="flex min-h-64 items-center justify-center"><Loader2 className="h-5 w-5 animate-spin"/></div>:rows.length===0?<div className="flex min-h-64 items-center justify-center p-8 text-sm text-muted-foreground">No attendance sessions yet.</div>:<div className="divide-y">{rows.map(s=><div key={s.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><p className="font-medium">{s.person?.full_name??'Unknown user'}</p><Badge variant="outline">{s.type}</Badge></div><p className="mt-1 text-xs text-muted-foreground">@{s.person?.username??'unknown'} · {s.source}</p></div><div className="text-sm sm:text-right"><p className="font-medium">{new Date(s.started_at).toLocaleString()}</p><p className="text-xs text-muted-foreground">{s.ended_at?`${new Date(s.ended_at).toLocaleString()} · ${duration(s).toFixed(2)}h`:'Currently open'} <Clock className="ml-1 inline h-3 w-3"/></p></div></div>)}</div>}</Card></div>
}
