import { useEffect } from 'react'
import { Activity, ArrowUpRight, CheckCircle2, Clock3, Package, Ticket, Users, AlertTriangle } from 'lucide-react'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import Loader from '@/components/Loader'
import { useAuth } from '@/lib/auth'
import { useAnalytics } from '@/hooks/useAnalytics'
import { useToast } from '@/hooks/use-toast'
import { useNavigate } from 'react-router-dom'
import { useDashboardTab } from '@/context/DashboardTabContext'

interface Props { activeTab?: string }
export default function AdminDashboard({activeTab='overview'}:Props){
 const {user,company}=useAuth();const {toast}=useToast();const navigate=useNavigate();const {setActiveTab}=useDashboardTab();const {counts,metrics,employeeStats,ticketTrend,loading,error,fetchAnalytics}=useAnalytics()
 useEffect(()=>{setActiveTab(activeTab);void fetchAnalytics()},[activeTab,fetchAnalytics,setActiveTab])
 if(loading)return <Loader/>
 if(error)return <div className="flex min-h-[60vh] flex-col items-center justify-center gap-4 p-6 text-center"><AlertTriangle className="h-10 w-10 text-destructive"/><h2 className="text-xl font-semibold">Unable to load dashboard</h2><p className="max-w-md text-sm text-muted-foreground">{error}</p><Button onClick={()=>void fetchAnalytics()}>Try again</Button></div>
 const cards=[['Team members',counts.users_total,Users,'/app/users'],['Assets',counts.assets_total,Package,'/app/assets'],['Tickets',counts.tickets_total,Ticket,'/app/tickets'],['Unresolved',counts.tickets_unresolved,AlertTriangle,'/app/tickets']] as const
 const trendMax=Math.max(1,...ticketTrend.map(x=>Math.max(x.created,x.resolved)));const utilization=metrics.utilizationRate
 return <div className="space-y-6">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">Dashboard</h1><Badge variant="secondary">Admin</Badge></div><p className="mt-1 text-sm text-muted-foreground">Welcome back, {user?.full_name??'Administrator'}{company?.name?` · ${company.name}`:''}</p></div><Button variant="outline" onClick={()=>{void fetchAnalytics();toast({title:'Dashboard refreshed'})}}><Activity className="mr-2 h-4 w-4"/>Refresh</Button></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon,href])=><Card key={label} className="group cursor-pointer p-5 transition-transform hover:-translate-y-0.5" onClick={()=>navigate(href)}><div className="flex items-start justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight">{value}</p></div><div className="rounded-xl border bg-muted/40 p-2.5"><Icon className="h-5 w-5"/></div></div><div className="mt-4 flex items-center text-xs text-muted-foreground">Open section<ArrowUpRight className="ml-1 h-3.5 w-3.5"/></div></Card>)}</div>
  <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Card className="p-5"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Ticket activity</h2><p className="text-sm text-muted-foreground">Created vs resolved over the last 30 days.</p></div><Badge variant="outline">{counts.tickets_total} total</Badge></div><div className="mt-6 flex h-56 items-end gap-1 overflow-hidden">{ticketTrend.map(day=><div key={day.date} className="flex h-full flex-1 items-end gap-px" title={`${day.date}: ${day.created} created, ${day.resolved} resolved`}><div className="w-1/2 rounded-t bg-foreground/20" style={{height:`${Math.max(2,day.created/trendMax*100)}%`}}/><div className="w-1/2 rounded-t bg-foreground" style={{height:`${Math.max(2,day.resolved/trendMax*100)}%`}}/></div>)}</div><div className="mt-4 flex gap-4 text-xs text-muted-foreground"><span>Created</span><span>Resolved</span></div></Card>
  <Card className="p-5"><h2 className="font-semibold">Asset utilization</h2><p className="text-sm text-muted-foreground">Currently assigned inventory.</p><div className="mt-8 flex justify-center"><div className="relative grid h-40 w-40 place-items-center rounded-full border-[14px] border-muted" style={{background:`conic-gradient(currentColor ${utilization}%, transparent 0)`}}><div className="grid h-28 w-28 place-items-center rounded-full bg-card text-center"><p className="text-3xl font-semibold">{utilization}%</p><p className="text-xs text-muted-foreground">utilized</p></div></div></div><div className="mt-6 grid grid-cols-2 gap-3 text-center"><div className="rounded-xl border p-3"><p className="text-lg font-semibold">{counts.asset_assignments_active}</p><p className="text-xs text-muted-foreground">Assigned</p></div><div className="rounded-xl border p-3"><p className="text-lg font-semibold">{metrics.availableAssets}</p><p className="text-xs text-muted-foreground">Available</p></div></div></Card></div>
  <Card className="overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">Team performance</h2><p className="text-sm text-muted-foreground">Ticket activity by active member.</p></div><Button variant="ghost" onClick={()=>navigate('/app/users')}>View people<ArrowUpRight className="ml-1 h-4 w-4"/></Button></div>{employeeStats.length===0?<div className="p-10 text-center text-sm text-muted-foreground">No employee activity yet.</div>:<div className="divide-y">{employeeStats.slice(0,8).map(e=><div key={e.userId} className="flex items-center justify-between gap-4 p-4"><div className="min-w-0"><p className="truncate font-medium">{e.fullName}</p><p className="text-xs text-muted-foreground">{e.ticketsCreated} created · {e.assetsAssigned} assets</p></div><div className="flex items-center gap-4 text-sm"><span className="flex items-center gap-1 text-muted-foreground"><CheckCircle2 className="h-4 w-4"/>{e.ticketsResolved}</span><span className="flex items-center gap-1 text-muted-foreground"><Clock3 className="h-4 w-4"/>{e.avgResolutionTime}h</span></div></div>)}</div>}</Card>
 </div>
}
