import { useEffect, useState } from 'react'
import { Plus } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '@/lib/supabase'
import type { Ticket } from '@/types/database'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'

interface AssetTicketWidgetProps{assetId:string;onCreateTicket?:()=>void}
type TicketSummary=Pick<Ticket,'id'|'ticket_number'|'subject'|'description'|'status'|'priority'|'created_at'>
const statusClass:Record<string,string>={open:'bg-red-50 text-red-700',in_progress:'bg-amber-50 text-amber-700',pending:'bg-slate-100 text-slate-700',resolved:'bg-emerald-50 text-emerald-700',closed:'bg-slate-100 text-slate-600'}
export function AssetTicketWidget({assetId,onCreateTicket}:AssetTicketWidgetProps){const navigate=useNavigate();const [tickets,setTickets]=useState<TicketSummary[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{let active=true;const load=async()=>{setLoading(true);try{const links=await supabase.from('asset_tickets').select('ticket_id').eq('asset_id',assetId);if(links.error)throw links.error;const ids=(links.data??[]).map(x=>x.ticket_id);if(!ids.length){if(active)setTickets([]);return}const result=await supabase.from('tickets').select('id,ticket_number,subject,description,status,priority,created_at').in('id',ids).order('created_at',{ascending:false});if(result.error)throw result.error;if(active)setTickets((result.data??[]) as TicketSummary[])}catch(error){console.error('Error loading asset tickets:',error);if(active)setTickets([])}finally{if(active)setLoading(false)}};void load();return()=>{active=false}},[assetId]);return <Card className="overflow-hidden"><CardHeader className="flex flex-row items-center justify-between border-b p-4 lg:p-5"><CardTitle className="text-base">Related tickets</CardTitle>{onCreateTicket&&<Button size="sm" onClick={onCreateTicket}><Plus className="mr-2 h-4 w-4"/>New ticket</Button>}</CardHeader><CardContent className="p-4 lg:p-5">{loading?<div className="py-8 text-center text-sm text-muted-foreground">Loading tickets…</div>:tickets.length===0?<div className="py-8 text-center text-sm text-muted-foreground">No tickets are linked to this asset.</div>:<div className="space-y-2">{tickets.slice(0,8).map(ticket=><button key={ticket.id} className="w-full rounded-xl border p-3 text-left transition-colors hover:bg-muted/40" onClick={()=>navigate(`/app/tickets/${ticket.id}`)}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-medium">{ticket.subject}</p><p className="mt-1 text-xs text-muted-foreground">TKT-{ticket.ticket_number}</p></div><Badge className={`shrink-0 capitalize ${statusClass[ticket.status]||''}`}>{ticket.status.replace('_',' ')}</Badge></div><div className="mt-2 flex items-center justify-between text-xs text-muted-foreground"><span className="capitalize">{ticket.priority}</span><span>{new Date(ticket.created_at).toLocaleDateString()}</span></div></button>)}</div>}</CardContent></Card>}
