import { useCallback, useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/lib/auth'
import { useToast } from '@/hooks/use-toast'
import type { Asset, AssetFilters, AssetImage } from '@/types/database'

const ASSET_COLUMNS='id,company_id,asset_tag,name,description,category,manufacturer,model,serial_number,status,condition,purchase_date,purchase_cost,warranty_expires_at,location,notes,metadata,created_by,created_at,updated_at,archived_at'

export function useAssets(){
 const [assets,setAssets]=useState<Asset[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const {user}=useAuth();const {toast}=useToast()
 const fetchAssets=useCallback(async(filters?:AssetFilters)=>{if(!user?.company_id){setAssets([]);setLoading(false);setError(null);return}try{setLoading(true);let query=supabase.from('assets').select(ASSET_COLUMNS).eq('company_id',user.company_id).is('archived_at',null).order('created_at',{ascending:false}).limit(500);if(filters?.status)query=query.eq('status',filters.status);if(filters?.category)query=query.eq('category',filters.category);if(filters?.search){const term=filters.search.trim().replace(/[%_,]/g,' ');if(term)query=query.or(`name.ilike.%${term}%,serial_number.ilike.%${term}%,asset_tag.ilike.%${term}%,manufacturer.ilike.%${term}%,model.ilike.%${term}%`)}const {data,error:assetError}=await query;if(assetError)throw assetError;const rows=(data??[]) as unknown as Asset[];if(!rows.length){setAssets([]);setError(null);return}const ids=rows.map(x=>x.id);const [assignRes,imageRes]=await Promise.all([supabase.from('asset_assignments').select('asset_id,assigned_to,assigned_at').in('asset_id',ids).is('returned_at',null),supabase.from('asset_images').select('asset_id,storage_path,is_primary,created_at').in('asset_id',ids).order('created_at',{ascending:false})]);if(assignRes.error)throw assignRes.error;if(imageRes.error)throw imageRes.error;const assignments=new Map((assignRes.data??[]).map(x=>[x.asset_id,x]));const primary=new Map<string,string>();for(const image of (imageRes.data??[]) as unknown as Pick<AssetImage,'asset_id'|'storage_path'|'is_primary'>[])if(!primary.has(image.asset_id)||image.is_primary)primary.set(image.asset_id,image.storage_path);const signedUrls=new Map<string,string>();const paths=[...primary.values()];if(paths.length){const signed=await supabase.storage.from('asset-images').createSignedUrls(paths,3600);if(!signed.error)paths.forEach((path,i)=>{const url=signed.data?.[i]?.signedUrl;if(url)signedUrls.set(path,url)})}let normalized=rows.map(asset=>{const assignment=assignments.get(asset.id);const imagePath=primary.get(asset.id);return{...asset,assigned_to:assignment?.assigned_to??null,assigned_at:assignment?.assigned_at??null,primary_image_url:imagePath?signedUrls.get(imagePath)??null:null} as Asset&{primary_image_url:string|null}});if(filters?.assignedTo)normalized=normalized.filter(asset=>asset.assigned_to===filters.assignedTo);setAssets(normalized as Asset[]);setError(null)}catch(err){const message=err instanceof Error?err.message:'Failed to load assets';setError(message);toast({title:'Error loading assets',description:message,variant:'destructive'})}finally{setLoading(false)}},[toast,user?.company_id])
 const getAssetById=useCallback(async(id:string)=>{if(!user?.company_id||!id)return null;const {data,error}=await supabase.from('assets').select(ASSET_COLUMNS).eq('id',id).eq('company_id',user.company_id).is('archived_at',null).single();if(error)throw error;return data as unknown as Asset},[user?.company_id])
 const createAsset=useCallback(async(input:Partial<Asset>&{name:string;asset_tag:string})=>{if(!user?.id||!user.company_id)throw new Error('User is not authenticated or has no company.');const payload={company_id:user.company_id,asset_tag:input.asset_tag.trim(),name:input.name.trim(),description:input.description??null,category:input.category??null,manufacturer:input.manufacturer??null,model:input.model??null,serial_number:input.serial_number??null,status:input.status??'active',condition:input.condition??'new',purchase_date:input.purchase_date??null,purchase_cost:input.purchase_cost??null,warranty_expires_at:input.warranty_expires_at??null,location:input.location??null,notes:input.notes??null,metadata:input.metadata??{},created_by:user.id};const {data,error}=await supabase.from('assets').insert(payload).select(ASSET_COLUMNS).single();if(error)throw error;await fetchAssets();toast({title:'Asset created',description:'The asset was added to inventory.'});return data as unknown as Asset},[fetchAssets,toast,user?.company_id,user?.id])
 const updateAsset=useCallback(async(id:string,updates:Partial<Asset>)=>{if(!user?.company_id)throw new Error('No company associated with the authenticated user.');const payload={...updates,updated_at:new Date().toISOString()};delete (payload as Record<string,unknown>).id;delete (payload as Record<string,unknown>).company_id;delete (payload as Record<string,unknown>).created_at;delete (payload as Record<string,unknown>).archived_at;const {error}=await supabase.from('assets').update(payload).eq('id',id).eq('company_id',user.company_id);if(error)throw error;await fetchAssets();toast({title:'Asset updated',description:'The asset was updated successfully.'})},[fetchAssets,toast,user?.company_id])
 const archiveAsset=useCallback(async(id:string)=>{if(!user?.company_id)throw new Error('No company associated with the authenticated user.');const {error}=await supabase.from('assets').update({archived_at:new Date().toISOString()}).eq('id',id).eq('company_id',user.company_id);if(error)throw error;setAssets(current=>current.filter(asset=>asset.id!==id));toast({title:'Asset archived',description:'The asset was removed from active inventory.'})},[toast,user?.company_id])
 useEffect(()=>{if(!user?.company_id)return;void fetchAssets();const channel=supabase.channel(`assets:${user.company_id}`).on('postgres_changes',{event:'*',schema:'public',table:'assets',filter:`company_id=eq.${user.company_id}`},()=>void fetchAssets()).subscribe();return()=>{void supabase.removeChannel(channel)}},[fetchAssets,user?.company_id])
 return{assets,loading,error,fetchAssets,getAssetById,createAsset,updateAsset,archiveAsset}
}
