import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/lib/auth'

export type ProfileSummary = { id:string; username:string; full_name:string; avatar_path:string|null; is_online:boolean; last_seen_at:string|null }
export type Conversation = { id:string; company_id:string; kind:string; title:string|null; avatar_path:string|null; created_by:string; created_at:string; updated_at:string; members?: ConversationMember[]; unread_count?:number }
export type ConversationMember = { conversation_id:string; user_id:string; role:string; joined_at:string; last_read_at:string|null; muted_until:string|null; archived_at:string|null; profile?: ProfileSummary }
export type MessageAttachment = { id:string; message_id:string; storage_path:string; file_name:string; mime_type:string; file_size_bytes:number; width:number|null; height:number|null; duration_seconds:number|null; url?:string }
export type MessageReaction = { message_id:string; user_id:string; reaction:string; created_at:string }
export type Message = { id:string; conversation_id:string; sender_id:string; message_type:string; body:string|null; reply_to_id:string|null; metadata:Record<string,unknown>; edited_at:string|null; deleted_at:string|null; created_at:string; updated_at:string; sender?: ProfileSummary; attachments?:MessageAttachment[]; reactions?:MessageReaction[] }

const attachmentBucket='message-attachments'

export function useCommunications(activeConversationId?: string|null) {
 const {user,company}=useAuth(); const [conversations,setConversations]=useState<Conversation[]>([]); const [messages,setMessages]=useState<Message[]>([]); const [people,setPeople]=useState<ProfileSummary[]>([]); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [error,setError]=useState<string|null>(null); const [typingUsers,setTypingUsers]=useState<ProfileSummary[]>([]); const typingChannel=useRef<ReturnType<typeof supabase.channel>|null>(null)
 const loadConversations=useCallback(async()=>{if(!user?.id)return;const {data,error}=await supabase.from('conversation_members').select('conversation_id,role,joined_at,last_read_at,muted_until,archived_at,conversations!inner(id,company_id,kind,title,avatar_path,created_by,created_at,updated_at)').eq('user_id',user.id).is('archived_at',null).order('joined_at',{ascending:false});if(error){setError(error.message);return}const rows=(data??[]).map((r:any)=>r.conversations).filter(Boolean) as Conversation[];if(!rows.length){setConversations([]);return}const ids=rows.map(r=>r.id);const {data:members}=await supabase.from('conversation_members').select('conversation_id,user_id,role,joined_at,last_read_at,muted_until,archived_at,profiles!conversation_members_user_id_fkey(id,username,full_name,avatar_path,is_online,last_seen_at)').in('conversation_id',ids);const {data:latest}=await supabase.from('messages').select('conversation_id,created_at,sender_id').in('conversation_id',ids).order('created_at',{ascending:false}).limit(Math.max(ids.length*20,200));const byId=new Map<string,ConversationMember[]>();for(const row of (members??[]) as any[]){const item={...row,profile:row.profiles};delete item.profiles;const list=byId.get(row.conversation_id)??[];list.push(item);byId.set(row.conversation_id,list)}const latestById=new Map<string,any>();for(const m of (latest??[]) as any[])if(!latestById.has(m.conversation_id))latestById.set(m.conversation_id,m);const unreadById=new Map<string,number>();for(const m of (latest??[]) as any[]){const own=(data??[]).find((r:any)=>r.conversation_id===m.conversation_id) as any;if(m.sender_id!==user.id&&(!own?.last_read_at||new Date(m.created_at)>new Date(own.last_read_at)))unreadById.set(m.conversation_id,(unreadById.get(m.conversation_id)??0)+1)}setConversations(rows.map(c=>{const ms=byId.get(c.id)??[];const other=ms.find(m=>m.user_id!==user.id);const displayTitle=c.title??(c.kind==='direct'?other?.profile?.username?`@${other.profile.username}`:other?.profile?.full_name??'Direct message':c.kind==='team'?'Team conversation':'Group conversation');return {...c,members:ms,title:displayTitle,unread_count:unreadById.get(c.id)??0,updated_at:latestById.get(c.id)?.created_at??c.updated_at}}).sort((a,b)=>new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime()))},[user?.id])
 const loadPeople=useCallback(async()=>{if(!company?.id)return;const {data}=await supabase.from('company_memberships').select('user_id,profiles!inner(id,username,full_name,avatar_path,is_online,last_seen_at)').eq('company_id',company.id).eq('is_active',true).neq('user_id',user?.id??'');setPeople((data??[]).map((r:any)=>r.profiles).filter(Boolean) as ProfileSummary[])},[company?.id,user?.id])
 const enrichMessages=useCallback(async(rows:any[])=>{if(!rows.length)return [] as Message[];const ids=rows.map(m=>m.id);const [{data:attachments},{data:reactions}]=await Promise.all([supabase.from('message_attachments').select('*').in('message_id',ids),supabase.from('conversation_message_reactions').select('*').in('message_id',ids)]);const attachmentMap=new Map<string,MessageAttachment[]>();for(const a of (attachments??[]) as any[]){const list=attachmentMap.get(a.message_id)??[];list.push(a);attachmentMap.set(a.message_id,list)}const reactionMap=new Map<string,MessageReaction[]>();for(const r of (reactions??[]) as any[]){const list=reactionMap.get(r.message_id)??[];list.push(r);reactionMap.set(r.message_id,list)}return rows.map(m=>({...m,attachments:attachmentMap.get(m.id)??[],reactions:reactionMap.get(m.id)??[]})) as Message[]},[])
 const loadMessages=useCallback(async(conversationId:string)=>{const {data,error}=await supabase.from('messages').select('*,sender:profiles!messages_sender_id_fkey(id,username,full_name,avatar_path,is_online,last_seen_at)').eq('conversation_id',conversationId).order('created_at',{ascending:true}).limit(200);if(error){setError(error.message);return}const enriched=await enrichMessages((data??[]) as any[]);const withUrls=await Promise.all(enriched.map(async m=>({...m,attachments:await Promise.all((m.attachments??[]).map(async a=>{const {data}=await supabase.storage.from(attachmentBucket).createSignedUrl(a.storage_path,3600);return {...a,url:data?.signedUrl}}))})));setMessages(withUrls);if(user?.id&&data?.length){const unread=(data as any[]).filter(m=>m.sender_id!==user.id&&!m.deleted_at).map(m=>({message_id:m.id,user_id:user.id,read_at:new Date().toISOString()}));if(unread.length)await supabase.from('message_read_receipts').upsert(unread,{onConflict:'message_id,user_id'});await supabase.from('conversation_members').update({last_read_at:new Date().toISOString()}).eq('conversation_id',conversationId).eq('user_id',user.id);await loadConversations()}},[user?.id,enrichMessages,loadConversations])
 useEffect(()=>{let alive=true;(async()=>{setLoading(true);await Promise.all([loadConversations(),loadPeople()]);if(alive)setLoading(false)})();return()=>{alive=false}},[loadConversations,loadPeople]);useEffect(()=>{if(activeConversationId)void loadMessages(activeConversationId);else setMessages([])},[activeConversationId,loadMessages])
 useEffect(()=>{if(!user?.id)return;const channel=supabase.channel(`communications:${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'conversation_members',filter:`user_id=eq.${user.id}`},()=>void loadConversations()).subscribe();return()=>{void supabase.removeChannel(channel)}},[user?.id,loadConversations])
 useEffect(()=>{if(!activeConversationId)return;const channel=supabase.channel(`conversation:${activeConversationId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${activeConversationId}`},async payload=>{if(payload.new.sender_id===user?.id)return;const [enriched]=await enrichMessages([payload.new]);setMessages(prev=>prev.some(m=>m.id===payload.new.id)?prev:[...prev,enriched]);if(user?.id)await supabase.from('message_read_receipts').upsert({message_id:payload.new.id,user_id:user.id,read_at:new Date().toISOString()},{onConflict:'message_id,user_id'})}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'messages',filter:`conversation_id=eq.${activeConversationId}`},payload=>setMessages(prev=>prev.map(m=>m.id===payload.new.id?{...m,...payload.new}:m))).on('postgres_changes',{event:'*',schema:'public',table:'conversation_message_reactions'},async payload=>{const id=(payload.new as any)?.message_id??(payload.old as any)?.message_id;if(!id)return;const {data}=await supabase.from('conversation_message_reactions').select('*').eq('message_id',id);setMessages(prev=>prev.map(m=>m.id===id?{...m,reactions:(data??[]) as MessageReaction[]}:m))}).subscribe();return()=>{void supabase.removeChannel(channel)}},[activeConversationId,user?.id,enrichMessages])
 useEffect(()=>{if(!activeConversationId||!user?.id)return;const channel=supabase.channel(`typing:${activeConversationId}`,{config:{broadcast:{self:false}}});typingChannel.current=channel;channel.on('broadcast',{event:'typing'},async({payload})=>{const p=payload as {userId:string;typing:boolean};if(p.userId===user.id)return;const {data}=await supabase.from('profiles').select('id,username,full_name,avatar_path,is_online,last_seen_at').eq('id',p.userId).maybeSingle();if(!data)return;setTypingUsers(prev=>p.typing?(prev.some(x=>x.id===data.id)?prev:[...prev,data as ProfileSummary]):prev.filter(x=>x.id!==data.id))}).subscribe();return()=>{void supabase.removeChannel(channel);typingChannel.current=null;setTypingUsers([])}},[activeConversationId,user?.id])
 const broadcastTyping=useCallback((typing:boolean)=>{if(user?.id)void typingChannel.current?.send({type:'broadcast',event:'typing',payload:{userId:user.id,typing}})},[user?.id])
 const startDirectMessage=useCallback(async(otherUserId:string)=>{const {data,error}=await supabase.rpc('create_direct_conversation',{p_other_user_id:otherUserId});if(error)throw error;await loadConversations();return data as string},[loadConversations])
 const sendMessage=useCallback(async(body:string,replyToId?:string|null,type='text',metadata:Record<string,unknown>={})=>{if(!user?.id||!activeConversationId||(!body.trim()&&type==='text'))return;setSending(true);setError(null);broadcastTyping(false);const {data,error}=await supabase.from('messages').insert({conversation_id:activeConversationId,sender_id:user.id,message_type:type,body:body.trim()||null,reply_to_id:replyToId??null,metadata}).select('*,sender:profiles!messages_sender_id_fkey(id,username,full_name,avatar_path,is_online,last_seen_at)').single();setSending(false);if(error){setError(error.message);throw error}setMessages(prev=>prev.some(m=>m.id===data.id)?prev:[...prev,{...data,attachments:[],reactions:[]} as Message]);await loadConversations()},[user?.id,activeConversationId,broadcastTyping,loadConversations])
 const sendAttachment=useCallback(async(file:File,caption='')=>{if(!user?.id||!activeConversationId)throw new Error('Select a conversation first');const ext=file.name.includes('.')?file.name.split('.').pop()?.toLowerCase():'bin';const path=`${activeConversationId}/${user.id}/${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await supabase.storage.from(attachmentBucket).upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const messageType=file.type.startsWith('image/')?'image':file.type.startsWith('video/')?'video':file.type.startsWith('audio/')?'audio':'file';const {data:message,error}=await supabase.from('messages').insert({conversation_id:activeConversationId,sender_id:user.id,message_type:messageType,body:caption.trim()||null,metadata:{file_name:file.name}}).select('*,sender:profiles!messages_sender_id_fkey(id,username,full_name,avatar_path,is_online,last_seen_at)').single();if(error){await supabase.storage.from(attachmentBucket).remove([path]);throw error}const {data:attachment,error:attachmentError}=await supabase.from('message_attachments').insert({message_id:message.id,storage_path:path,file_name:file.name,mime_type:file.type,file_size_bytes:file.size}).select('*').single();if(attachmentError){await supabase.from('messages').delete().eq('id',message.id);await supabase.storage.from(attachmentBucket).remove([path]);throw attachmentError}const {data:signed}=await supabase.storage.from(attachmentBucket).createSignedUrl(path,3600);setMessages(prev=>[...prev,{...message,attachments:[{...attachment,url:signed?.signedUrl}],reactions:[]} as Message]);await loadConversations()},[user?.id,activeConversationId,loadConversations])
 const toggleReaction=useCallback(async(messageId:string,reaction:string)=>{if(!user?.id)return;const {data:existing}=await supabase.from('conversation_message_reactions').select('message_id').eq('message_id',messageId).eq('user_id',user.id).eq('reaction',reaction).maybeSingle();if(existing)await supabase.from('conversation_message_reactions').delete().eq('message_id',messageId).eq('user_id',user.id).eq('reaction',reaction);else await supabase.from('conversation_message_reactions').insert({message_id:messageId,user_id:user.id,reaction})},[user?.id])
 const startCall=useCallback(async(callType:'audio'|'video'='video')=>{if(!activeConversationId)throw new Error('Select a conversation first');const {data,error}=await supabase.rpc('start_call',{p_conversation_id:activeConversationId,p_call_type:callType});if(error)throw error;return data as string},[activeConversationId])
 const activeConversation=useMemo(()=>conversations.find(c=>c.id===activeConversationId)??null,[conversations,activeConversationId]);return {conversations,people,messages,activeConversation,typingUsers,loading,sending,error,startDirectMessage,sendMessage,sendAttachment,toggleReaction,broadcastTyping,startCall,refresh:loadConversations}
}
