import { useCallback, useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/lib/auth'
import { useToast } from '@/hooks/use-toast'
import type { TicketPriority, TicketStatus } from '@/types/database'

export interface TicketWithHistory { id:string;ticket_number:number;company_id:string;subject:string;title?:string;description:string|null;status:TicketStatus;priority:TicketPriority;channel:string;category_id:string|null;department_id:string|null;team_id:string|null;requester_id:string;created_by:string;accepted_by:string|null;accepted_at:string|null;resolved_at:string|null;closed_at:string|null;due_at:string|null;first_response_due_at:string|null;first_responded_at:string|null;sla_breached_at:string|null;waiting_reason:string|null;escalation_level:number;archived_at:string|null;metadata:Record<string,unknown>;created_at:string;updated_at:string;assigned_to?:string|null;category?:{id:string;name:string}|null;creator?:{id:string;full_name:string}|null;requester?:{id:string;full_name:string}|null;assignee?:{id:string;full_name:string}|null;assignment?:{id:string;assignee_id:string;assigned_at:string;unassigned_at:string|null;department_id:string|null;team_id:string|null;assignee?:{id:string;full_name:string}|null}|null;status_history?:Array<{id:string;from_status:TicketStatus|null;to_status:TicketStatus;changed_by:string|null;changed_at:string;note:string|null}> }
export type TicketFilters={companyId?:string;status?:TicketStatus;assignedTo?:string;assetId?:string;teamId?:string;departmentId?:string;priority?:TicketPriority;search?:string;archived?:boolean;createdBy?:string}
type Cursor={created_at:string;id:string}|null
const COLUMNS=`id,ticket_number,company_id,subject,description,status,priority,channel,category_id,department_id,team_id,requester_id,created_by,accepted_by,accepted_at,resolved_at,closed_at,due_at,first_response_due_at,first_responded_at,sla_breached_at,waiting_reason,escalation_level,archived_at,metadata,created_at,updated_at,category:ticket_categories!tickets_category_id_fkey(id,name),creator:profiles!tickets_created_by_fkey(id,full_name),requester:profiles!tickets_requester_id_fkey(id,full_name),assignment:ticket_assignments!ticket_assignments_ticket_id_fkey(id,assignee_id,assigned_at,unassigned_at,department_id,team_id,assignee:profiles!ticket_assignments_assignee_id_fkey(id,full_name)),status_history:ticket_status_history(id,from_status,to_status,changed_by,changed_at,note)`
const normalize=(row:any):TicketWithHistory=>{const a=Array.isArray(row.assignment)?row.assignment.find((x:any)=>!x.unassigned_at)??null:row.assignment??null;const one=(v:any)=>Array.isArray(v)?v[0]??null:v??null;return{...row,title:String(row.subject??''),assigned_to:a?.assignee_id??null,assignment:a,assignee:one(a?.assignee),category:one(row.category),creator:one(row.creator),requester:one(row.requester),status_history:Array.isArray(row.status_history)?row.status_history:[],metadata:row.metadata&&typeof row.metadata==='object'?row.metadata:{}}}
export function useTickets(){
 const{user}=useAuth();const{toast}=useToast();const[tickets,setTickets]=useState<TicketWithHistory[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[cursor,setCursor]=useState<Cursor>(null);const[hasMore,setHasMore]=useState(false);const[activeFilters,setActiveFilters]=useState<TicketFilters>({});
 const fetchTickets=useCallback(async(filters:TicketFilters={},options:{showLoading?:boolean;append?:boolean}={})=>{if(!user?.company_id){setTickets([]);setLoading(false);return}const append=options.append===true;if(options.showLoading!==false)setLoading(true);const f={...filters,companyId:user.company_id};try{const result=await supabase.rpc('search_tickets',{p_company_id:user.company_id,p_cursor_created_at:append?cursor?.created_at:null,p_cursor_id:append?cursor?.id:null,p_limit:50,p_status:f.status??null,p_assignee_id:f.assignedTo??null,p_asset_id:f.assetId??null,p_team_id:f.teamId??null,p_department_id:f.departmentId??null,p_priority:f.priority??null,p_search:f.search?.trim()||null,p_archived:f.archived??false,p_created_by:f.createdBy??null});if(result.error)throw result.error;const payload=result.data as any;const rows=((payload?.items??[])as any[]).map(normalize);setTickets(prev=>append?[...prev,...rows]:rows);setHasMore(Boolean(payload?.has_more));setCursor(payload?.next_cursor??null);setActiveFilters(f);setError(null)}catch(e){const message=e instanceof Error?e.message:'Failed to load tickets';setError(message);toast({title:'Error loading tickets',description:message,variant:'destructive'})}finally{setLoading(false)}},[cursor,toast,user?.company_id])
 const loadNextPage=useCallback(()=>{if(!hasMore||loading)return Promise.resolve();return fetchTickets(activeFilters,{append:true,showLoading:false})},[activeFilters,fetchTickets,hasMore,loading])
 const updateTicketStatus=useCallback(async(ticketId:string,newStatus:TicketStatus,note?:string)=>{const{error}=await supabase.rpc('update_ticket_status',{p_ticket_id:ticketId,p_status:newStatus,p_note:note??null});if(error)throw error;toast({title:'Status updated'});await fetchTickets(activeFilters,{showLoading:false})},[activeFilters,fetchTickets,toast])
 const assignTicket=useCallback(async(ticketId:string,assigneeId:string,departmentId?:string|null,teamId?:string|null)=>{const{data:current,error:ce}=await supabase.from('tickets').select('department_id,team_id').eq('id',ticketId).eq('company_id',user?.company_id??'').single();if(ce)throw ce;const{error}=await supabase.rpc('assign_ticket',{p_ticket_id:ticketId,p_assignee_id:assigneeId,p_department_id:departmentId===undefined?current.department_id:departmentId,p_team_id:teamId===undefined?current.team_id:teamId});if(error)throw error;toast({title:'Ticket assigned'});await fetchTickets(activeFilters,{showLoading:false})},[activeFilters,fetchTickets,toast,user?.company_id])
 const acceptTicket=useCallback(async(ticketId:string)=>{const{error}=await supabase.rpc('accept_ticket',{p_ticket_id:ticketId});if(error)throw error;toast({title:'Ticket accepted'});await fetchTickets(activeFilters,{showLoading:false})},[activeFilters,fetchTickets,toast])
 useEffect(()=>{if(!user?.company_id)return;void fetchTickets({}, {showLoading:true})},[user?.company_id])
 useEffect(()=>{if(!user?.company_id)return;const channel=supabase.channel(`tickets:${user.company_id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'tickets',filter:`company_id=eq.${user.company_id}`},async payload=>{const row=normalize(payload.new);if((activeFilters.archived??false)!==(!!row.archived_at))return;if(activeFilters.status&&row.status!==activeFilters.status)return;if(activeFilters.priority&&row.priority!==activeFilters.priority)return;if(activeFilters.assignedTo&&row.assigned_to!==activeFilters.assignedTo)return;if(activeFilters.createdBy&&row.created_by!==activeFilters.createdBy)return;setTickets(prev=>prev.some(t=>t.id===row.id)?prev:[row,...prev])}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'tickets',filter:`company_id=eq.${user.company_id}`},async payload=>{const{data,error}=await supabase.from('tickets').select(COLUMNS).eq('id',payload.new.id).maybeSingle();if(error||!data)return;const row=normalize(data);const visible=!(activeFilters.archived??false)?!row.archived_at:!!row.archived_at;const matches=visible&&(!activeFilters.status||row.status===activeFilters.status)&&(!activeFilters.priority||row.priority===activeFilters.priority)&&(!activeFilters.assignedTo||row.assigned_to===activeFilters.assignedTo)&&(!activeFilters.createdBy||row.created_by===activeFilters.createdBy);setTickets(prev=>matches?(prev.some(t=>t.id===row.id)?prev.map(t=>t.id===row.id?row:t):[row,...prev]):prev.filter(t=>t.id!==row.id))}).on('postgres_changes',{event:'DELETE',schema:'public',table:'tickets',filter:`company_id=eq.${user.company_id}`},payload=>setTickets(prev=>prev.filter(t=>t.id!==payload.old.id))).subscribe();return()=>{void supabase.removeChannel(channel)}},[activeFilters,user?.company_id])
 return{tickets,loading,error,fetchTickets,loadNextPage,hasMore,updateTicketStatus,assignTicket,acceptTicket}
}
