import { useCallback, useEffect, useRef, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/lib/auth'

type Signal={type:'offer'|'answer'|'ice-candidate';from:string;to:string;sdp?:RTCSessionDescriptionInit;candidate?:RTCIceCandidateInit}
const iceServers:RTCIceServer[]=[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}]
const turnUrl=import.meta.env.VITE_TURN_URL as string|undefined
const turnUsername=import.meta.env.VITE_TURN_USERNAME as string|undefined
const turnCredential=import.meta.env.VITE_TURN_CREDENTIAL as string|undefined
if(turnUrl&&turnUsername&&turnCredential)iceServers.push({urls:turnUrl,username:turnUsername,credential:turnCredential})

export function useWebRTCCall(callId:string|null,participantIds:string[],videoEnabled=true){
 const {user}=useAuth(); const [localStream,setLocalStream]=useState<MediaStream|null>(null); const [remoteStreams,setRemoteStreams]=useState<Record<string,MediaStream>>({}); const [muted,setMuted]=useState(false); const [videoOff,setVideoOff]=useState(!videoEnabled); const [sharing,setSharing]=useState(false); const pcs=useRef<Record<string,RTCPeerConnection>>({}); const pendingIce=useRef<Record<string,RTCIceCandidateInit[]>>({}); const channel=useRef<ReturnType<typeof supabase.channel>|null>(null); const streamRef=useRef<MediaStream|null>(null); const cameraTrack=useRef<MediaStreamTrack|null>(null); const shareStream=useRef<MediaStream|null>(null)
 const send=useCallback(async(signal:Signal)=>{await channel.current?.send({type:'broadcast',event:'signal',payload:signal})},[])
 const attachLocalTracks=useCallback((pc:RTCPeerConnection)=>{const stream=streamRef.current;if(!stream)return;for(const track of stream.getTracks())if(!pc.getSenders().some(sender=>sender.track?.kind===track.kind))pc.addTrack(track,stream)},[])
 const createPeer=useCallback((peerId:string)=>{if(!user?.id)return undefined;if(pcs.current[peerId]){attachLocalTracks(pcs.current[peerId]);return pcs.current[peerId]}const pc=new RTCPeerConnection({iceServers});pcs.current[peerId]=pc;attachLocalTracks(pc);pc.onicecandidate=e=>{if(e.candidate)void send({type:'ice-candidate',from:user.id,to:peerId,candidate:e.candidate.toJSON()})};pc.ontrack=e=>{const [stream]=e.streams;if(stream)setRemoteStreams(prev=>({...prev,[peerId]:stream}))};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState))setRemoteStreams(prev=>{const n={...prev};delete n[peerId];return n})};return pc},[user?.id,send,attachLocalTracks])
 useEffect(()=>{if(!callId||!user?.id)return;const c=supabase.channel(`webrtc:${callId}`,{config:{private:true,broadcast:{self:false,ack:true}}});channel.current=c;c.on('broadcast',{event:'signal'},async({payload})=>{const s=payload as Signal;if(s.to!==user.id)return;const pc=createPeer(s.from);if(!pc)return;if(s.type==='offer'&&s.sdp){await pc.setRemoteDescription(s.sdp);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await send({type:'answer',from:user.id,to:s.from,sdp:answer});const queued=pendingIce.current[s.from]??[];for(const candidate of queued)try{await pc.addIceCandidate(candidate)}catch{}delete pendingIce.current[s.from]}else if(s.type==='answer'&&s.sdp){await pc.setRemoteDescription(s.sdp);const queued=pendingIce.current[s.from]??[];for(const candidate of queued)try{await pc.addIceCandidate(candidate)}catch{}delete pendingIce.current[s.from]}else if(s.type==='ice-candidate'&&s.candidate){if(pc.remoteDescription)try{await pc.addIceCandidate(s.candidate)}catch{}else pendingIce.current[s.from]=[...(pendingIce.current[s.from]??[]),s.candidate]}}).subscribe();return()=>{void supabase.removeChannel(c);channel.current=null}},[callId,user?.id,createPeer,send])
 const start=useCallback(async()=>{if(streamRef.current)return streamRef.current;const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:videoEnabled});cameraTrack.current=stream.getVideoTracks()[0]??null;streamRef.current=stream;setLocalStream(stream);setVideoOff(!videoEnabled);Object.values(pcs.current).forEach(attachLocalTracks);return stream},[videoEnabled,attachLocalTracks])
 const connect=useCallback(async()=>{if(!user?.id)return;await start();for(const peerId of participantIds.filter(id=>id!==user.id)){const pc=createPeer(peerId);if(!pc)continue;const offer=await pc.createOffer();await pc.setLocalDescription(offer);await send({type:'offer',from:user.id,to:peerId,sdp:offer})}},[user?.id,participantIds,start,createPeer,send])
 const toggleAudio=useCallback(()=>{setMuted(prev=>{const next=!prev;streamRef.current?.getAudioTracks().forEach(t=>t.enabled=!next);return next})},[])
 const toggleVideo=useCallback(()=>{setVideoOff(prev=>{const next=!prev;streamRef.current?.getVideoTracks().forEach(t=>t.enabled=!next);return next})},[])
 const stopScreenShare=useCallback(async()=>{shareStream.current?.getTracks().forEach(t=>t.stop());for(const pc of Object.values(pcs.current)){const sender=pc.getSenders().find(s=>s.track?.kind==='video');if(sender&&cameraTrack.current)await sender.replaceTrack(cameraTrack.current)}shareStream.current=null;setSharing(false)},[])
 const toggleScreenShare=useCallback(async()=>{if(sharing){await stopScreenShare();return}const screen=await navigator.mediaDevices.getDisplayMedia({video:true});const track=screen.getVideoTracks()[0];shareStream.current=screen;for(const pc of Object.values(pcs.current)){const sender=pc.getSenders().find(s=>s.track?.kind==='video');if(sender)await sender.replaceTrack(track)}track.onended=()=>{void stopScreenShare()};setSharing(true)},[sharing,stopScreenShare])
 const leave=useCallback(()=>{Object.values(pcs.current).forEach(pc=>pc.close());pcs.current={};pendingIce.current={};shareStream.current?.getTracks().forEach(t=>t.stop());streamRef.current?.getTracks().forEach(t=>t.stop());shareStream.current=null;streamRef.current=null;setLocalStream(null);setRemoteStreams({});setSharing(false)},[])
 useEffect(()=>leave,[leave])
 return {localStream,remoteStreams,muted,videoOff,sharing,start,connect,toggleAudio,toggleVideo,toggleScreenShare,leave}
}
