import { useCallback, useEffect, useRef, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/lib/auth'

type Signal={type:'offer'|'answer'|'ice-candidate';from:string;to:string;sdp?:RTCSessionDescriptionInit;candidate?:RTCIceCandidateInit}

export function useWebRTCCall(callId:string|null,participantIds:string[],videoEnabled=true){
 const {user}=useAuth(); const [localStream,setLocalStream]=useState<MediaStream|null>(null); const [remoteStreams,setRemoteStreams]=useState<Record<string,MediaStream>>({}); const [muted,setMuted]=useState(false); const [videoOff,setVideoOff]=useState(!videoEnabled); const [sharing,setSharing]=useState(false); const pcs=useRef<Record<string,RTCPeerConnection>>({}); const channel=useRef<ReturnType<typeof supabase.channel>|null>(null); const streamRef=useRef<MediaStream|null>(null); const cameraTrack=useRef<MediaStreamTrack|null>(null); const shareStream=useRef<MediaStream|null>(null)
 const send=useCallback(async(signal:Signal)=>{await channel.current?.send({type:'broadcast',event:'signal',payload:signal})},[])
 const createPeer=useCallback((peerId:string)=>{if(!user?.id)return undefined;if(pcs.current[peerId])return pcs.current[peerId];const pc=new RTCPeerConnection({iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}]});pcs.current[peerId]=pc;streamRef.current?.getTracks().forEach(t=>pc.addTrack(t,streamRef.current!));pc.onicecandidate=e=>{if(e.candidate)void send({type:'ice-candidate',from:user.id,to:peerId,candidate:e.candidate.toJSON()})};pc.ontrack=e=>{const [stream]=e.streams;if(stream)setRemoteStreams(prev=>({...prev,[peerId]:stream}))};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState))setRemoteStreams(prev=>{const n={...prev};delete n[peerId];return n})};return pc},[user?.id,send])
 useEffect(()=>{if(!callId||!user?.id)return;const c=supabase.channel(`webrtc:${callId}`,{config:{broadcast:{self:false}}});channel.current=c;c.on('broadcast',{event:'signal'},async({payload})=>{const s=payload as Signal;if(s.to!==user.id)return;const pc=createPeer(s.from);if(!pc)return;if(s.type==='offer'&&s.sdp){await pc.setRemoteDescription(s.sdp);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await send({type:'answer',from:user.id,to:s.from,sdp:answer})}else if(s.type==='answer'&&s.sdp){await pc.setRemoteDescription(s.sdp)}else if(s.type==='ice-candidate'&&s.candidate){try{await pc.addIceCandidate(s.candidate)}catch{}}}).subscribe();return()=>{void supabase.removeChannel(c);channel.current=null}},[callId,user?.id,createPeer,send])
 const start=useCallback(async()=>{if(streamRef.current)return streamRef.current;const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:videoEnabled});cameraTrack.current=stream.getVideoTracks()[0]??null;streamRef.current=stream;setLocalStream(stream);setVideoOff(!videoEnabled);return stream},[videoEnabled])
 const connect=useCallback(async()=>{if(!user?.id)return;await start();for(const peerId of participantIds.filter(id=>id!==user.id)){const pc=createPeer(peerId);if(!pc)continue;const offer=await pc.createOffer();await pc.setLocalDescription(offer);await send({type:'offer',from:user.id,to:peerId,sdp:offer})}},[user?.id,participantIds,start,createPeer,send])
 const toggleAudio=useCallback(()=>{const next=!muted;streamRef.current?.getAudioTracks().forEach(t=>t.enabled=!next);setMuted(next)},[muted])
 const toggleVideo=useCallback(()=>{const next=!videoOff;streamRef.current?.getVideoTracks().forEach(t=>t.enabled=!next);setVideoOff(next)},[videoOff])
 const toggleScreenShare=useCallback(async()=>{if(sharing){shareStream.current?.getTracks().forEach(t=>t.stop());for(const pc of Object.values(pcs.current)){const sender=pc.getSenders().find(s=>s.track?.kind==='video');if(sender&&cameraTrack.current)await sender.replaceTrack(cameraTrack.current)}setSharing(false);return}const screen=await navigator.mediaDevices.getDisplayMedia({video:true});const track=screen.getVideoTracks()[0];shareStream.current=screen;for(const pc of Object.values(pcs.current)){const sender=pc.getSenders().find(s=>s.track?.kind==='video');if(sender)await sender.replaceTrack(track)}track.onended=()=>{void toggleScreenShare()};setSharing(true)},[sharing,toggleScreenShare])
 const leave=useCallback(()=>{Object.values(pcs.current).forEach(pc=>pc.close());pcs.current={};shareStream.current?.getTracks().forEach(t=>t.stop());streamRef.current?.getTracks().forEach(t=>t.stop());shareStream.current=null;streamRef.current=null;setLocalStream(null);setRemoteStreams({});setSharing(false)},[])
 useEffect(()=>leave,[leave])
 return {localStream,remoteStreams,muted,videoOff,sharing,start,connect,toggleAudio,toggleVideo,toggleScreenShare,leave}
}
