import { useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, Filter, RefreshCw, Search, UserCircle } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type AuditRow={id:string;company_id:string;actor_id:string|null;action:string;entity_type:string;entity_id:string|null;description:string|null;changes:Record<string,unknown>|null;metadata:Record<string,unknown>|null;occurred_at:string}
type Actor={id:string;full_name:string}

const ACTIONS=['all','create','update','delete','login','logout','access','export','invite','approve','reject']

export default function AuditPage(){
 const [rows,setRows]=useState<AuditRow[]>([]);const [actors,setActors]=useState<Record<string,Actor>>({});const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [query,setQuery]=useState('');const [action,setAction]=useState('all');const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{setError(null);const {data,error}=await supabase.from('audit_logs').select('id,company_id,actor_id,action,entity_type,entity_id,description,changes,metadata,occurred_at').order('occurred_at',{ascending:false}).limit(300);if(error){setError(error.message);setRows([]);return}const list=(data??[]) as AuditRow[];setRows(list);const ids=[...new Set(list.map(r=>r.actor_id).filter(Boolean))] as string[];if(ids.length){const {data:profiles}=await supabase.from('profiles').select('id,full_name').in('id',ids);setActors(Object.fromEntries(((profiles??[]) as Actor[]).map(p=>[p.id,p])))}},[])
 useEffect(()=>{void load().finally(()=>setLoading(false))},[load])
 const refresh=async()=>{setRefreshing(true);await load();setRefreshing(false)}
 const filtered=useMemo(()=>rows.filter(r=>{const hay=[r.description??'',r.entity_type,r.entity_id??'',actors[r.actor_id??'']?.full_name??'',r.action].join(' ').toLowerCase();return (action==='all'||r.action===action)&&hay.includes(query.toLowerCase())}),[rows,query,action,actors])
 return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><Activity className="h-5 w-5 text-primary"/><h1 className="text-2xl font-semibold tracking-tight">Audit activity</h1></div><p className="mt-1 text-sm text-muted-foreground">A chronological record of workspace actions and changes.</p></div><button onClick={()=>void refresh()} disabled={refreshing} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-border bg-card px-4 text-sm font-medium hover:bg-muted disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${refreshing?'animate-spin':''}`}/>Refresh</button></div>
 <div className="flex flex-col gap-3 rounded-xl border border-border bg-card p-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search activity, users or records" className="h-10 w-full rounded-lg border border-border bg-background pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-primary/20"/></div><div className="relative sm:w-44"><Filter className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><select value={action} onChange={e=>setAction(e.target.value)} className="h-10 w-full appearance-none rounded-lg border border-border bg-background pl-9 pr-3 text-sm outline-none"><option value="all">All actions</option>{ACTIONS.slice(1).map(a=><option key={a} value={a}>{a.charAt(0).toUpperCase()+a.slice(1)}</option>)}</select></div></div>
 <div className="overflow-hidden rounded-xl border border-border bg-card">{error&&<div className="border-b border-border bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}{loading?<div className="p-8 text-center text-sm text-muted-foreground">Loading audit activity…</div>:filtered.length===0?<div className="p-10 text-center"><Activity className="mx-auto mb-3 h-8 w-8 text-muted-foreground/50"/><p className="font-medium">No activity found</p><p className="mt-1 text-sm text-muted-foreground">Try a different search or action filter.</p></div>:<div className="divide-y divide-border">{filtered.map(row=><div key={row.id} className="flex gap-4 p-4 sm:p-5"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-primary/10 text-primary"><UserCircle className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-medium">{row.description||`${row.action} ${row.entity_type}`}</p><time className="shrink-0 text-xs text-muted-foreground">{new Date(row.occurred_at).toLocaleString()}</time></div><div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><span className="rounded-full bg-muted px-2 py-0.5 font-medium text-foreground">{row.action}</span><span>{actors[row.actor_id??'']?.full_name||'System'}</span><span>·</span><span>{row.entity_type}</span>{row.entity_id&&<><span>·</span><span className="font-mono">{row.entity_id.slice(0,8)}</span></>}</div>{row.changes&&Object.keys(row.changes).length>0&&<details className="mt-2 text-xs"><summary className="cursor-pointer text-muted-foreground">View changes</summary><pre className="mt-2 overflow-auto rounded-lg bg-muted p-3">{JSON.stringify(row.changes,null,2)}</pre></details>}</div></div>)}</div>}</div><p className="text-xs text-muted-foreground">Showing {filtered.length} of {rows.length} recent audit events.</p></div>
}
