import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { Mic, MicOff, Video, VideoOff, PhoneOff, Monitor, Loader2 } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/lib/auth'
import { useWebRTCCall } from '@/hooks/useWebRTCCall'

function initials(name:string){return name.split(/\s+/).map(p=>p[0]).join('').slice(0,2).toUpperCase()}
function VideoTile({stream,name,muted=false}:{stream:MediaStream|null;name:string;muted?:boolean}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{if(ref.current)ref.current.srcObject=stream;return()=>{if(ref.current)ref.current.srcObject=null}},[stream]);return <div className="relative min-h-[260px] overflow-hidden rounded-2xl bg-slate-900"><video ref={ref} autoPlay playsInline muted={muted} className="h-full min-h-[260px] w-full object-cover"/>{!stream&&<div className="absolute inset-0 grid place-items-center"><div className="grid h-20 w-20 place-items-center rounded-full bg-slate-700 text-xl font-semibold text-white">{initials(name)}</div></div>}<div className="absolute bottom-3 left-3 rounded-lg bg-black/50 px-2.5 py-1.5 text-xs font-medium text-white backdrop-blur">{name}</div></div>}

export default function CallPage(){
 const {callId,roomId}=useParams(); const [params]=useSearchParams(); const navigate=useNavigate(); const {user}=useAuth(); const [resolvedCallId,setResolvedCallId]=useState<string|null>(callId??null); const [call,setCall]=useState<any>(null); const [participants,setParticipants]=useState<any[]>([]); const [error,setError]=useState<string|null>(null); const [elapsed,setElapsed]=useState(0); const type=params.get('type')==='audio'?'audio':'video'
 useEffect(()=>{if(callId||!roomId||!user?.id)return;void (async()=>{const {data,error}=await supabase.rpc('start_team_call',{p_team_id:roomId,p_call_type:type});if(error){setError(error.message);return}setResolvedCallId(data as string);navigate(`/app/calls/${data}?type=${type}`,{replace:true})})()},[callId,roomId,user?.id,type,navigate])
 const ids=useMemo(()=>participants.map(p=>p.user_id),[participants]); const rtc=useWebRTCCall(resolvedCallId,ids,type==='video')
 useEffect(()=>{if(!resolvedCallId||!user?.id)return;let alive=true;(async()=>{const {data,error}=await supabase.from('calls').select('*').eq('id',resolvedCallId).single();if(error){if(alive)setError(error.message);return}const {data:ps,error:pe}=await supabase.from('call_participants_v2').select('call_id,user_id,role,status,profiles!call_participants_v2_user_id_fkey(id,full_name)').eq('call_id',resolvedCallId);if(pe){if(alive)setError(pe.message);return}if(alive){setCall(data);setParticipants(ps??[]);}})();const ch=supabase.channel(`call-state:${resolvedCallId}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'calls',filter:`id=eq.${resolvedCallId}`},p=>setCall(p.new)).on('postgres_changes',{event:'UPDATE',schema:'public',table:'call_participants_v2',filter:`call_id=eq.${resolvedCallId}`},p=>setParticipants(prev=>prev.map(x=>x.user_id===p.new.user_id?{...x,...p.new}:x))).subscribe();return()=>{alive=false;void supabase.removeChannel(ch)}},[resolvedCallId,user?.id])
 useEffect(()=>{if(!call||!user?.id)return;const mine=call.initiator_id===user.id;void rtc.start().then(()=>{if(mine)void rtc.connect()}).catch(e=>setError(e instanceof Error?e.message:'Could not access camera or microphone'));void supabase.rpc('update_call_status',{p_call_id:call.id,p_status:'connecting'}).catch(()=>{})},[call?.id,call?.initiator_id,user?.id,rtc.start,rtc.connect])
 useEffect(()=>{const i=setInterval(()=>setElapsed(v=>v+1),1000);return()=>clearInterval(i)},[])
 const leave=async()=>{if(resolvedCallId)await supabase.rpc('update_call_status',{p_call_id:resolvedCallId,p_status:'ended',p_reason:'left'});rtc.leave();navigate('/app/communications')}
 const mins=Math.floor(elapsed/60).toString().padStart(2,'0');const secs=(elapsed%60).toString().padStart(2,'0');
 return <div className="fixed inset-0 z-[100] flex flex-col bg-slate-950 text-white"><header className="flex h-16 items-center justify-between border-b border-white/10 px-5"><div><p className="text-sm font-semibold">{type==='video'?'Video call':'Audio call'}</p><p className="text-xs text-slate-400">{call?.status==='ringing'?'Ringing…':`${mins}:${secs}`}</p></div><div className="text-xs text-slate-400">{participants.length} participant{participants.length===1?'':'s'}</div></header><main className="min-h-0 flex-1 overflow-auto p-4 md:p-6"><div className={`mx-auto grid h-full max-w-6xl gap-4 ${Object.keys(rtc.remoteStreams).length>1?'md:grid-cols-2':'md:grid-cols-[minmax(0,1fr)_280px]'}`}><div className="min-h-[320px]"><VideoTile stream={type==='video'?rtc.localStream:null} name="You" muted/><div className="mt-3 text-xs text-slate-400">{error||'Secure peer-to-peer media connection'}</div></div>{participants.filter(p=>p.user_id!==user?.id).map(p=><VideoTile key={p.user_id} stream={rtc.remoteStreams[p.user_id]??null} name={p.profiles?.full_name||`User ${p.user_id.slice(0,6)}`}/>)}</div></main><footer className="flex h-24 items-center justify-center gap-3 border-t border-white/10"><button onClick={rtc.toggleAudio} className="grid h-12 w-12 place-items-center rounded-full bg-white/10 hover:bg-white/20">{rtc.muted?<MicOff/>:<Mic/>}</button>{type==='video'&&<button onClick={rtc.toggleVideo} className="grid h-12 w-12 place-items-center rounded-full bg-white/10 hover:bg-white/20">{rtc.videoOff?<VideoOff/>:<Video/>}</button>}{type==='video'&&<button onClick={()=>void rtc.toggleScreenShare()} className={`grid h-12 w-12 place-items-center rounded-full ${rtc.sharing?'bg-primary':'bg-white/10'} hover:bg-white/20`} title="Screen sharing"><Monitor/></button>}<button onClick={()=>void leave()} className="grid h-12 w-14 place-items-center rounded-full bg-red-600 hover:bg-red-500"><PhoneOff/></button></footer>{!call&&!error&&<div className="absolute inset-0 grid place-items-center bg-slate-950/90"><Loader2 className="h-8 w-8 animate-spin"/></div>}</div>
}
