import { useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { MessageCircle, Search, Video, Phone, Send, Plus, Check, Smile, MoreVertical, ArrowLeft, Paperclip, FileText } from 'lucide-react'
import { useCommunications } from '@/hooks/useCommunications'
import { useAuth } from '@/lib/auth'

function initials(name:string){return name.split(/\s+/).map(p=>p[0]).join('').slice(0,2).toUpperCase()}
function Avatar({name,online=false}:{name:string;online?:boolean}){return <span className="relative grid h-11 w-11 shrink-0 place-items-center rounded-full bg-primary/10 text-sm font-semibold text-primary">{initials(name)}{online&&<span className="absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-card bg-emerald-500"/>}</span>}
function formatSize(bytes:number){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${Math.round(bytes/1024)} KB`;return `${(bytes/1024/1024).toFixed(1)} MB`}

export default function CommunicationsPage(){
 const {user}=useAuth(); const navigate=useNavigate(); const [selected,setSelected]=useState<string|null>(null); const [query,setQuery]=useState(''); const [draft,setDraft]=useState(''); const [showPeople,setShowPeople]=useState(false); const [replyTo,setReplyTo]=useState<string|null>(null); const fileRef=useRef<HTMLInputElement>(null)
 const {conversations,people,messages,activeConversation,typingUsers,loading,sending,error,startDirectMessage,sendMessage,sendAttachment,toggleReaction,broadcastTyping,startCall}=useCommunications(selected)
 const filtered=useMemo(()=>conversations.filter(c=>(c.title??'').toLowerCase().includes(query.toLowerCase())||c.kind.toLowerCase().includes(query.toLowerCase())),[conversations,query])
 const send=async()=>{if(!draft.trim()||sending)return;const value=draft;setDraft('');try{await sendMessage(value,replyTo);setReplyTo(null)}catch{setDraft(value)}}
 const beginCall=async(type:'audio'|'video')=>{try{const id=await startCall(type);navigate(`/app/calls/${id}?type=${type}`)}catch(err){console.error(err)}}
 const upload=async(file?:File)=>{if(!file)return;try{await sendAttachment(file); }catch(err){console.error(err)}}
 return <div className="flex h-[calc(100vh-2rem)] min-h-[620px] overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
   <aside className={`flex w-full max-w-[360px] flex-col border-r border-border ${selected?'hidden lg:flex':''}`}>
    <div className="border-b border-border p-4"><div className="mb-4 flex items-center justify-between"><div><h1 className="text-xl font-semibold tracking-tight">Messages</h1><p className="text-xs text-muted-foreground">Direct and team communication</p></div><button onClick={()=>setShowPeople(v=>!v)} className="grid h-9 w-9 place-items-center rounded-lg bg-primary text-primary-foreground" title="New message"><Plus className="h-4 w-4"/></button></div><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search conversations" className="h-10 w-full rounded-lg border border-border bg-background pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-primary/20"/></div></div>
    {showPeople&&<div className="border-b border-border bg-muted/30 p-3"><p className="mb-2 px-1 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Start a conversation</p>{people.slice(0,12).map(person=>person&&<button key={person.id} onClick={async()=>{const id=await startDirectMessage(person.id);setSelected(id);setShowPeople(false)}} className="flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left hover:bg-background"><Avatar name={person.full_name} online={person.is_online}/><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{person.full_name}</span><span className="text-xs text-muted-foreground">{person.is_online?'Online':person.last_seen_at?`Last seen ${new Date(person.last_seen_at).toLocaleDateString()}`:'Offline'}</span></span></button>)}</div>}
    <div className="min-h-0 flex-1 overflow-y-auto">{loading?<div className="p-6 text-sm text-muted-foreground">Loading conversations…</div>:filtered.length===0?<div className="flex h-full flex-col items-center justify-center p-8 text-center"><MessageCircle className="mb-3 h-8 w-8 text-muted-foreground"/><p className="font-medium">No conversations yet</p><p className="mt-1 text-xs text-muted-foreground">Start a message with someone in your workspace.</p></div>:filtered.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={`flex w-full items-center gap-3 border-b border-border/70 px-4 py-3 text-left transition ${selected===c.id?'bg-primary/5':'hover:bg-muted/50'}`}><Avatar name={c.title||'Conversation'}/><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className="block truncate text-sm font-semibold">{c.title||'Conversation'}</span>{!!c.unread_count&&<span className="grid min-w-5 place-items-center rounded-full bg-primary px-1.5 py-0.5 text-[10px] font-semibold text-primary-foreground">{c.unread_count>99?'99+':c.unread_count}</span>}</span><span className="block truncate text-xs text-muted-foreground">{c.kind==='direct'?'Direct message':c.kind}</span></span><span className="text-[10px] text-muted-foreground">{new Date(c.updated_at).toLocaleDateString()}</span></button>)}</div>}
   </aside>
   <section className={`flex min-w-0 flex-1 flex-col ${!selected?'hidden lg:flex':''}`}>
    {!activeConversation?<div className="flex h-full flex-col items-center justify-center text-center"><MessageCircle className="mb-4 h-12 w-12 text-muted-foreground/50"/><h2 className="text-lg font-semibold">Your messages</h2><p className="mt-1 max-w-sm text-sm text-muted-foreground">Select a conversation or start a new one. Messages and calls are tied to real user IDs.</p></div>:<>
      <header className="flex h-16 items-center gap-3 border-b border-border px-4"><button onClick={()=>setSelected(null)} className="grid h-9 w-9 place-items-center rounded-lg hover:bg-muted lg:hidden"><ArrowLeft className="h-4 w-4"/></button><Avatar name={activeConversation.title||'Conversation'}/><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold">{activeConversation.title||'Conversation'}</h2><p className="text-xs text-muted-foreground">{activeConversation.kind==='direct'?'Private conversation':'Group conversation'}</p></div><button onClick={()=>void beginCall('audio')} className="grid h-9 w-9 place-items-center rounded-lg hover:bg-muted" title="Audio call"><Phone className="h-4 w-4"/></button><button onClick={()=>void beginCall('video')} className="grid h-9 w-9 place-items-center rounded-lg hover:bg-muted" title="Video call"><Video className="h-4 w-4"/></button><button className="grid h-9 w-9 place-items-center rounded-lg hover:bg-muted"><MoreVertical className="h-4 w-4"/></button></header>
      <div className="min-h-0 flex-1 space-y-2 overflow-y-auto bg-background/60 p-4">{messages.map(m=>{const mine=m.sender_id===user?.id;const reactionCounts=(m.reactions??[]).reduce<Record<string,number>>((a,r)=>(a[r.reaction]=(a[r.reaction]??0)+1,a),{});return <div key={m.id} className={`group flex ${mine?'justify-end':'justify-start'}`}><div className={`max-w-[min(75%,620px)] ${mine?'items-end':'items-start'} flex flex-col`}><div className={`rounded-2xl px-3.5 py-2.5 text-sm shadow-sm ${mine?'rounded-br-md bg-primary text-primary-foreground':'rounded-bl-md border border-border bg-card'}`}>{m.deleted_at?<span className="italic opacity-60">Message deleted</span>:<>{m.attachments?.map(a=>a.url&&a.mime_type.startsWith('image/')?<img key={a.id} src={a.url} alt={a.file_name} className="mb-2 max-h-72 max-w-full rounded-lg object-cover"/>:a.url?<a key={a.id} href={a.url} target="_blank" rel="noreferrer" className="mb-2 flex items-center gap-2 rounded-lg bg-black/5 p-2 underline-offset-2 hover:underline"><FileText className="h-4 w-4 shrink-0"/><span className="min-w-0"><span className="block truncate">{a.file_name}</span><span className="text-[10px] opacity-70">{formatSize(a.file_size_bytes)}</span></span></a>:null)}{m.body&&<div>{m.body}</div>}</>}</div>{Object.entries(reactionCounts).length>0&&<div className="mt-1 flex flex-wrap gap-1">{Object.entries(reactionCounts).map(([emoji,count])=><button key={emoji} onClick={()=>void toggleReaction(m.id,emoji)} className="rounded-full border border-border bg-card px-2 py-0.5 text-xs">{emoji} {count}</button>)}</div>}<div className="mt-1 flex items-center gap-2 px-1 text-[10px] text-muted-foreground opacity-0 transition group-hover:opacity-100"><span>{new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span><button onClick={()=>void toggleReaction(m.id,'❤️')} className="hover:text-primary">❤️</button><button onClick={()=>setReplyTo(m.id)} className="hover:text-primary">Reply</button>{mine&&<Check className="h-3 w-3"/>}</div></div></div>})}{typingUsers.length>0&&<div className="px-1 text-xs text-muted-foreground">Someone is typing…</div>}</div>
      {error&&<div className="border-t border-border bg-destructive/5 px-4 py-2 text-xs text-destructive">{error}</div>}
      {replyTo&&<div className="flex items-center justify-between border-t border-border bg-muted/40 px-4 py-2 text-xs"><span>Replying to a message</span><button onClick={()=>setReplyTo(null)} className="font-medium hover:underline">Cancel</button></div>}
      <div className="border-t border-border bg-card p-3"><input ref={fileRef} type="file" className="hidden" accept="image/*,video/*,audio/*,application/pdf,text/plain" onChange={e=>{void upload(e.target.files?.[0]);e.currentTarget.value=''}}/><div className="flex items-end gap-2 rounded-xl border border-border bg-background p-2"><button onClick={()=>fileRef.current?.click()} className="grid h-9 w-9 shrink-0 place-items-center rounded-lg hover:bg-muted" title="Attach file"><Paperclip className="h-5 w-5 text-muted-foreground"/></button><textarea value={draft} onChange={e=>{setDraft(e.target.value);broadcastTyping(e.target.value.length>0)}} onBlur={()=>broadcastTyping(false)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}} placeholder="Write a message…" rows={1} className="max-h-32 min-h-9 flex-1 resize-none bg-transparent px-1 py-2 text-sm outline-none"/><button onClick={()=>void send()} disabled={!draft.trim()||sending} className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-primary text-primary-foreground disabled:opacity-50"><Send className="h-4 w-4"/></button></div><p className="mt-1 px-2 text-[10px] text-muted-foreground">Enter to send · Shift+Enter for a new line · Attach images, video, audio or files</p></div>
    </>}
   </section>
 </div>
}
