import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Activity, ArrowUpRight, BarChart3, Bell, Building2, CheckCircle2, Clock3, FolderOpen, Package, Plus, Ticket, Users } from 'lucide-react'
import { useAuth } from '@/lib/auth'
import { useAnalytics } from '@/hooks/useAnalytics'
import { getExactCompanyCounts, type ExactCompanyCounts } from '@/lib/dataAccess'
import { supabase } from '@/lib/supabase'
import Loader from '@/components/Loader'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'

const EMPTY_COUNTS: ExactCompanyCounts = { users_total:0, users_unique:0, departments_total:0, teams_total:0, ticket_categories_total:0, tickets_total:0, tickets_open:0, tickets_in_progress:0, tickets_pending:0, tickets_resolved:0, tickets_closed:0, tickets_unresolved:0, tickets_overdue:0, assets_total:0, asset_assignments_active:0, ticket_assignments_active:0, ticket_comments_total:0, ticket_attachments_total:0, workspace_folders_total:0, workspace_files_total:0, notifications_unread:0, attendance_today:0, qr_codes_active:0, qr_scans_today:0, video_calls_total:0, video_calls_active:0, subscriptions_total:0, payments_total:0, audit_logs_total:0 }
type Icon = typeof Activity

function Metric({ label, value, icon: IconComponent, detail, onClick, tone = 'blue' }: { label:string; value:number|string; icon:Icon; detail:string; onClick?:()=>void; tone?:'blue'|'green'|'amber'|'slate' }) {
  const toneClass = { blue:'bg-primary/10 text-primary', green:'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400', amber:'bg-amber-500/10 text-amber-600 dark:text-amber-400', slate:'bg-muted text-muted-foreground' }[tone]
  return <Card onClick={onClick} className={`group border-border/80 bg-card p-5 shadow-none transition-all hover:-translate-y-0.5 hover:shadow-lg ${onClick ? 'cursor-pointer' : ''}`}><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-xs font-medium uppercase tracking-[0.12em] text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1.5 text-xs text-muted-foreground">{detail}</p></div><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${toneClass}`}><IconComponent className="h-[18px] w-[18px]"/></span></div></Card>
}

export default function DashboardPage() {
  const { user, company } = useAuth(); const navigate = useNavigate(); const { metrics, ticketTrend, loading: analyticsLoading, error: analyticsError, fetchAnalytics } = useAnalytics()
  const [counts, setCounts] = useState<ExactCompanyCounts>(EMPTY_COUNTS); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const loadDashboard = async () => { if (!user?.company_id) return; try { setCounts(await getExactCompanyCounts(user.company_id)); await fetchAnalytics() } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load dashboard') } }
  useEffect(() => { if (!user?.company_id) return; let cancelled = false; setLoading(true); Promise.all([getExactCompanyCounts(user.company_id), fetchAnalytics()]).then(([nextCounts]) => { if (!cancelled) setCounts(nextCounts) }).catch(err => { if (!cancelled) setError(err instanceof Error ? err.message : 'Unable to load dashboard') }).finally(() => { if (!cancelled) setLoading(false) }); const channel = supabase.channel(`dashboard-${user.company_id}`).on('postgres_changes', { event:'*', schema:'public', table:'tickets', filter:`company_id=eq.${user.company_id}` }, loadDashboard).on('postgres_changes', { event:'*', schema:'public', table:'assets', filter:`company_id=eq.${user.company_id}` }, loadDashboard).on('postgres_changes', { event:'*', schema:'public', table:'company_memberships', filter:`company_id=eq.${user.company_id}` }, loadDashboard).subscribe(); return () => { cancelled = true; supabase.removeChannel(channel) } }, [user?.company_id, fetchAnalytics])
  if (!user || loading || analyticsLoading) return <Loader />

  const resolved = counts.tickets_resolved + counts.tickets_closed; const openWork = counts.tickets_open + counts.tickets_in_progress + counts.tickets_pending; const recentTrend = ticketTrend.slice(-7); const maxTrend = Math.max(1, ...recentTrend.map(p => Math.max(p.created, p.resolved))); const canManageUsers = user.role === 'admin' || user.role === 'hr'
  const quickAccess:[string,number,Icon,string][] = [['Tickets', counts.tickets_total, Ticket, '/app/tickets'], ['Assets', counts.assets_total, Package, '/app/assets'], ['Departments', counts.departments_total, Building2, '/app/departments'], ['Teams', counts.teams_total, Users, '/app/teams'], ['Files', counts.workspace_files_total, FolderOpen, '/app/workspace']]
  return <div className="space-y-7">
    <section className="flex flex-col gap-5 rounded-2xl border border-border bg-card p-6 shadow-sm sm:p-7 lg:flex-row lg:items-end lg:justify-between">
      <div><div className="mb-3 flex items-center gap-2 text-xs font-medium text-muted-foreground"><span className="h-2 w-2 rounded-full bg-emerald-500"/> All systems operational</div><p className="text-sm font-semibold text-primary">{company?.name || 'Workspace'}</p><h2 className="mt-1 text-3xl font-semibold tracking-[-0.035em] sm:text-4xl">Good to see you, {user.full_name?.split(' ')[0] || 'there'}.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">A clear view of your support operation, people and resources.</p></div>
      <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => navigate('/app/notifications')}><Bell className="mr-2 h-4 w-4"/>Notifications{counts.notifications_unread > 0 && <span className="ml-2 rounded-full bg-primary px-1.5 text-[10px] text-primary-foreground">{counts.notifications_unread}</span>}</Button><Button onClick={() => navigate('/app/tickets/new')}><Plus className="mr-2 h-4 w-4"/>New ticket</Button></div>
    </section>
    {(error || analyticsError) && <Card className="border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{error || analyticsError}</Card>}

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total tickets" value={counts.tickets_total} detail={`${openWork} currently active`} icon={Ticket} tone="blue" onClick={() => navigate('/app/tickets')}/><Metric label="Resolved" value={resolved} detail={`${counts.tickets_total ? Math.round(resolved / counts.tickets_total * 100) : 0}% resolution rate`} icon={CheckCircle2} tone="green" onClick={() => navigate('/app/tickets')}/><Metric label="Assets" value={counts.assets_total} detail={`${metrics.availableAssets} currently available`} icon={Package} tone="amber" onClick={() => navigate('/app/assets')}/><Metric label="Team members" value={counts.users_total} detail={`${counts.teams_total} active teams`} icon={Users} tone="slate" onClick={canManageUsers ? () => navigate('/app/users') : undefined}/></section>

    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.8fr)_minmax(320px,1fr)]">
      <Card className="overflow-hidden border-border bg-card shadow-none"><div className="flex items-center justify-between border-b border-border px-5 py-5 sm:px-6"><div><p className="text-xs font-medium uppercase tracking-[0.12em] text-muted-foreground">Performance</p><h3 className="mt-1 text-lg font-semibold">Ticket activity</h3></div><div className="rounded-xl bg-primary/10 p-2 text-primary"><BarChart3 className="h-4 w-4"/></div></div><div className="px-5 pb-5 pt-6 sm:px-6"><div className="flex h-52 items-end gap-2 sm:gap-4">{recentTrend.map(point => <div key={point.date} className="flex min-w-0 flex-1 flex-col items-center gap-2"><div className="flex h-40 w-full items-end justify-center gap-1 rounded-lg bg-muted/30 px-1"><div className="w-2 rounded-t bg-primary/25 transition-all" style={{ height:`${Math.max(5, point.created / maxTrend * 100)}%` }}/><div className="w-2 rounded-t bg-primary transition-all" style={{ height:`${Math.max(5, point.resolved / maxTrend * 100)}%` }}/></div><span className="text-[10px] font-medium text-muted-foreground">{new Date(point.date).toLocaleDateString(undefined, { weekday:'short' })}</span></div>)}{!recentTrend.length && <div className="grid w-full place-items-center text-sm text-muted-foreground">No ticket activity yet.</div>}</div><div className="mt-5 flex gap-5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-primary/25"/>Created</span><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-primary"/>Resolved</span></div></div></Card>
      <Card className="border-border bg-card shadow-none"><div className="flex items-center justify-between border-b border-border px-5 py-5 sm:px-6"><div><p className="text-xs font-medium uppercase tracking-[0.12em] text-muted-foreground">Navigation</p><h3 className="mt-1 text-lg font-semibold">Quick access</h3></div><ArrowUpRight className="h-4 w-4 text-muted-foreground"/></div><div className="space-y-1 p-3">{quickAccess.map(([label,value,IconComponent,href]) => { const I = IconComponent; return <button key={label} onClick={() => navigate(href)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left transition-colors hover:bg-muted"><span className="grid h-9 w-9 place-items-center rounded-lg bg-muted"><I className="h-4 w-4 text-muted-foreground"/></span><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{label}</span><span className="block text-[11px] text-muted-foreground">Open section</span></span><span className="text-sm font-semibold text-muted-foreground">{value}</span></button> })}{canManageUsers && <button onClick={() => navigate('/app/users')} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left transition-colors hover:bg-muted"><span className="grid h-9 w-9 place-items-center rounded-lg bg-muted"><Users className="h-4 w-4 text-muted-foreground"/></span><span className="min-w-0 flex-1"><span className="block text-sm font-medium">Users</span><span className="block text-[11px] text-muted-foreground">Manage access</span></span><span className="text-sm font-semibold text-muted-foreground">{counts.users_total}</span></button>}</div></Card>
    </section>

    <section className="grid gap-4 sm:grid-cols-3"><Card className="border-border bg-card p-5 shadow-none"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Clock3 className="h-4 w-4"/></span><div><p className="text-xs text-muted-foreground">Avg. resolution</p><p className="mt-1 text-xl font-semibold">{metrics.avgResolutionTime ? `${metrics.avgResolutionTime.toFixed(1)}h` : '—'}</p></div></div></Card><Card className="border-border bg-card p-5 shadow-none"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-500/10 text-amber-600"><Package className="h-4 w-4"/></span><div><p className="text-xs text-muted-foreground">Asset utilization</p><p className="mt-1 text-xl font-semibold">{metrics.utilizationRate}%</p></div></div></Card><Card className="border-border bg-card p-5 shadow-none"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-500/10 text-emerald-600"><Activity className="h-4 w-4"/></span><div><p className="text-xs text-muted-foreground">Active assignments</p><p className="mt-1 text-xl font-semibold">{counts.ticket_assignments_active}</p></div></div></Card></section>
  </div>
}
