import { useEffect, useMemo, useState } from 'react'
import { Building2, Plus, Search, Users, ArrowRight } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '@/lib/auth'
import { supabase } from '@/lib/supabase'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import Loader from '@/components/Loader'
import { useToast } from '@/hooks/use-toast'

type Department={id:string;company_id:string;name:string;description:string|null;manager_id:string|null;created_at:string;updated_at:string;manager?:{full_name:string;phone:string|null}|null;memberCount:number}
export default function DepartmentsPage(){
 const {user}=useAuth();const {toast}=useToast();const navigate=useNavigate();const [departments,setDepartments]=useState<Department[]>([]);const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [form,setForm]=useState({name:'',description:''})
 const load=async()=>{if(!user?.company_id)return;setLoading(true);try{const {data,error}=await supabase.from('departments').select('id,company_id,name,description,manager_id,created_at,updated_at,profiles!departments_manager_id_fkey(full_name,phone)').eq('company_id',user.company_id).order('created_at',{ascending:false});if(error)throw error;const rows=await Promise.all((data??[]).map(async d=>{const {count,error:ce}=await supabase.from('company_memberships').select('*',{count:'exact',head:true}).eq('company_id',user.company_id).eq('department_id',d.id).eq('is_active',true);if(ce)throw ce;return {...d,manager:Array.isArray(d.profiles)?d.profiles[0]??null:d.profiles??null,memberCount:count??0}}));setDepartments(rows as Department[])}catch(e){toast({title:'Departments unavailable',description:e instanceof Error?e.message:'Failed to load departments.',variant:'destructive'})}finally{setLoading(false)}}
 useEffect(()=>{void load()},[user?.company_id])
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return departments.filter(d=>!q||`${d.name} ${d.description??''} ${d.manager?.full_name??''}`.toLowerCase().includes(q))},[departments,search])
 const create=async(e:React.FormEvent)=>{e.preventDefault();if(!user?.company_id)return;const name=form.name.trim();const description=form.description.trim();if(!name){toast({title:'Department name required',description:'Enter a department name before saving.',variant:'destructive'});return}setSaving(true);try{const payload={company_id:user.company_id,name,description:description||null};const {error}=await supabase.from('departments').insert(payload);if(error)throw error;toast({title:'Department created'});setForm({name:'',description:''});setOpen(false);await load()}catch(e){toast({title:'Create failed',description:e instanceof Error?e.message:'Unable to create department.',variant:'destructive'})}finally{setSaving(false)}}
 return <div className="space-y-6"><div className="flex justify-end"><Button onClick={()=>setOpen(true)}><Plus className="mr-2 h-4 w-4"/>Create department</Button></div><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" placeholder="Search departments..." value={search} onChange={e=>setSearch(e.target.value)}/></div>{loading?<Loader/>:visible.length===0?<Card className="p-12 text-center"><Building2 className="mx-auto mb-3 h-9 w-9 text-muted-foreground"/><p className="font-medium">No departments found</p></Card>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visible.map(d=><Card key={d.id} className="group cursor-pointer p-5 transition-transform hover:-translate-y-0.5" onClick={()=>navigate(`/app/departments/${d.id}`)}><div className="flex items-start justify-between gap-4"><div className="rounded-xl border bg-muted/40 p-3"><Building2 className="h-5 w-5"/></div><ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-1"/></div><h2 className="mt-5 font-semibold">{d.name}</h2><p className="mt-1 min-h-10 text-sm text-muted-foreground">{d.description??'No description provided.'}</p><div className="mt-5 flex items-center justify-between border-t pt-4"><span className="flex items-center gap-2 text-sm text-muted-foreground"><Users className="h-4 w-4"/>{d.memberCount} active members</span><Badge variant="outline">{d.manager?.full_name??'No manager'}</Badge></div></Card>)}</div>}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-lg overflow-hidden p-0"><DialogHeader className="border-b border-border bg-card px-6 py-5 text-left"><DialogTitle className="text-lg font-semibold">Create department</DialogTitle><p className="mt-1 text-sm text-muted-foreground">Add a department to this company workspace.</p></DialogHeader><form onSubmit={create} className="bg-card"><div className="space-y-5 px-6 py-6"><div className="space-y-2"><Label htmlFor="department-name">Department name</Label><Input id="department-name" required autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. IT Support"/></div><div className="space-y-2"><Label htmlFor="department-description">Description <span className="font-normal text-muted-foreground">(optional)</span></Label><Textarea id="department-description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Briefly describe the department's responsibility."/></div></div><DialogFooter className="border-t border-border bg-muted/20 px-6 py-4"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving} type="submit">{saving?'Creating…':'Create department'}</Button></DialogFooter></form></DialogContent></Dialog></div>
}
