import { useEffect, useRef, useState } from 'react'
import jsQR from 'jsqr'
import { useNavigate } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { useAttendance } from '@/hooks/useAttendance'
import { useToast } from '@/hooks/use-toast'
import { useAuth } from '@/lib/auth'

export default function QRScannerPage(){
 const navigate=useNavigate();const{user}=useAuth();const{toast}=useToast();const{attendanceStatus,registerAttendance,fetchAttendanceStatus,loading}=useAttendance();const videoRef=useRef<HTMLVideoElement>(null);const canvasRef=useRef<HTMLCanvasElement>(null);const[manual,setManual]=useState('');const[scanning,setScanning]=useState(false);const[history,setHistory]=useState<{sessions:number;hours:number}>({sessions:0,hours:0});
 useEffect(()=>{void fetchAttendanceStatus()},[fetchAttendanceStatus])
 useEffect(()=>{if(!user?.id)return;let cancelled=false;const load=async()=>{const from=new Date();from.setDate(from.getDate()-30);const{data}=await (await import('@/lib/supabase')).supabase.from('attendance_sessions').select('started_at,ended_at,type').eq('company_id',user.company_id).eq('user_id',user.id).gte('started_at',from.toISOString());if(cancelled)return;const sessions=data??[];const hours=sessions.filter(s=>s.type==='work').reduce((n,s)=>n+(new Date(s.ended_at??new Date().toISOString()).getTime()-new Date(s.started_at).getTime())/3600000,0);setHistory({sessions:sessions.length,hours})};void load();return()=>{cancelled=true}},[user?.company_id,user?.id,attendanceStatus.status])
 useEffect(()=>{if(!scanning)return;let active=true;let stream:MediaStream|null=null;const run=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});if(!videoRef.current)return;videoRef.current.srcObject=stream;await videoRef.current.play();const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)return;const tick=()=>{if(!active)return;const video=videoRef.current;if(video&&video.readyState>=2){canvas.width=video.videoWidth;canvas.height=video.videoHeight;ctx.drawImage(video,0,0,canvas.width,canvas.height);const image=ctx.getImageData(0,0,canvas.width,canvas.height);const code=jsQR(image.data,image.width,image.height);if(code){setScanning(false);void handleScan(code.data);return}}requestAnimationFrame(tick)};requestAnimationFrame(tick)}catch(e){toast({title:'Camera unavailable',description:e instanceof Error?e.message:'Unable to access the camera.',variant:'destructive'});setScanning(false)}};void run();return()=>{active=false;stream?.getTracks().forEach(t=>t.stop());if(videoRef.current)videoRef.current.srcObject=null}},[scanning])
 const handleScan=async(value:string)=>{try{const result=await registerAttendance(value);toast({title:result.action==='clock_in'?'Clocked in':'Clocked out',description:'Attendance was recorded successfully.'})}catch(e){toast({title:'Scan failed',description:e instanceof Error?e.message:'Unable to record attendance.',variant:'destructive'})}}
 const submit=async()=>{if(!manual.trim())return;await handleScan(manual.trim());setManual('')}
 return <div className="mx-auto w-full max-w-3xl space-y-6"><div><h1 className="text-2xl font-semibold">QR attendance</h1><p className="mt-1 text-sm text-muted-foreground">Scan a company attendance QR code. Attendance is recorded as an individual session.</p></div><Card className="overflow-hidden"><div className="aspect-video bg-muted">{scanning?<video ref={videoRef} className="h-full w-full object-cover" muted playsInline/>:<div className="grid h-full place-items-center text-sm text-muted-foreground">Camera is off</div>}</div><canvas ref={canvasRef} className="hidden"/><div className="flex gap-2 p-4"><Button onClick={()=>setScanning(v=>!v)} disabled={loading}>{scanning?'Stop scanner':'Start scanner'}</Button><Button variant="outline" onClick={()=>navigate('/app/users?tab=attendance')}>View attendance</Button></div></Card><Card className="p-5"><p className="text-sm text-muted-foreground">Current status</p><p className="mt-1 text-xl font-semibold">{attendanceStatus.status.replace('_',' ')}</p><p className="mt-1 text-sm text-muted-foreground">{attendanceStatus.elapsedHours??'No open work session'}</p></Card><Card className="p-5"><h2 className="font-semibold">Manual QR entry</h2><div className="mt-3 flex gap-2"><Input value={manual} onChange={e=>setManual(e.target.value)} placeholder="attendance://code"/><Button onClick={()=>void submit()} disabled={loading||!manual.trim()}>Submit</Button></div></Card><Card className="p-5"><h2 className="font-semibold">Last 30 days</h2><p className="mt-2 text-sm text-muted-foreground">{history.sessions} recorded sessions · {history.hours.toFixed(1)} work hours</p>{history.sessions===0&&<p className="mt-2 text-sm text-muted-foreground">No attendance data yet.</p>}</Card></div>
}
