import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AlertCircle, Edit2, Home, Loader2, MessageSquare, Plus, Search, Trash2, Users } from 'lucide-react'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'
import Loader from '@/components/Loader'
import TeamChatView from '@/components/teams/TeamChatView'
import { supabase } from '@/lib/supabase'
import { fetchSupabasePage } from '@/lib/dataAccess'
import { useAuth } from '@/lib/auth'
import { useToast } from '@/hooks/use-toast'

interface Team { id:string; company_id:string; name:string; description:string|null; created_by:string|null; team_lead_id:string|null; avatar_color:string|null; created_at:string; updated_at:string; member_count:number; is_member:boolean; user_role:'lead'|'member'|null }
const colors=['from-primary to-cyan-500','from-violet-500 to-fuchsia-500','from-emerald-500 to-teal-500','from-amber-500 to-orange-500','from-rose-500 to-pink-500']
const initials=(name:string)=>name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()

export default function TeamsPage(){
 const navigate=useNavigate(); const {user}=useAuth(); const {toast}=useToast(); const companyId=user?.company_id; const userId=user?.id
 const [teams,setTeams]=useState<Team[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [search,setSearch]=useState(''); const [selected,setSelected]=useState<string|null>(null); const [mobileList,setMobileList]=useState(true)
 const [createOpen,setCreateOpen]=useState(false); const [editOpen,setEditOpen]=useState(false); const [deleteOpen,setDeleteOpen]=useState(false); const [editing,setEditing]=useState<Team|null>(null); const [deleting,setDeleting]=useState<Team|null>(null); const [saving,setSaving]=useState(false); const [form,setForm]=useState({name:'',description:''})
 const loadTeams=useCallback(async()=>{if(!companyId||!userId)return;try{setLoading(true);setError(null);const page=await fetchSupabasePage<any>('teams',0,{pageSize:1000,columns:'id,company_id,name,description,created_by,team_lead_id,avatar_color,created_at,updated_at',orderBy:'updated_at'});const rows=page.data.filter(t=>t.company_id===companyId);const ids=rows.map(t=>t.id);const membership=ids.length?await supabase.from('team_members').select('team_id,role').eq('user_id',userId).in('team_id',ids):{data:[],error:null};if(membership.error)throw membership.error;const map=new Map((membership.data??[]).map(m=>[m.team_id,m.role]));const counts=ids.length?await supabase.from('team_members').select('team_id').in('team_id',ids):{data:[],error:null};if(counts.error)throw counts.error;const countMap=new Map<string,number>();(counts.data??[]).forEach(m=>countMap.set(m.team_id,(countMap.get(m.team_id)??0)+1));setTeams(rows.map(t=>({...t,member_count:countMap.get(t.id)??0,is_member:map.has(t.id),user_role:map.get(t.id)==='lead'?'lead':map.has(t.id)?'member':null}))) }catch(e){setError(e instanceof Error?e.message:'Failed to load teams');toast({title:'Unable to load teams',description:'Please try again.',variant:'destructive'})}finally{setLoading(false)}},[companyId,userId,toast])
 useEffect(()=>{loadTeams();if(!companyId)return;const channel=supabase.channel(`teams:${companyId}`).on('postgres_changes',{event:'*',schema:'public',table:'teams',filter:`company_id=eq.${companyId}`},loadTeams).subscribe();return()=>{supabase.removeChannel(channel)}},[companyId,loadTeams])
 const visible=useMemo(()=>teams.filter(t=>t.is_member&&(t.name.toLowerCase().includes(search.toLowerCase())||(t.description??'').toLowerCase().includes(search.toLowerCase()))),[teams,search]); const selectedTeam=teams.find(t=>t.id===selected)||null
 const createTeam=async()=>{if(!companyId||!userId)return;const name=form.name.trim();const description=form.description.trim();if(!name){setError('Team name is required');return}setSaving(true);try{const teamPayload={company_id:companyId,name,description:description||null,created_by:userId,team_lead_id:userId};const {data,error}=await supabase.from('teams').insert(teamPayload).select('id').single();if(error)throw error;const memberPayload={team_id:data.id,user_id:userId,role:'lead'};const member=await supabase.from('team_members').insert(memberPayload);if(member.error)throw member.error;setForm({name:'',description:''});setCreateOpen(false);await loadTeams();setSelected(data.id);setMobileList(false);toast({title:'Team created',description:'Your team is ready.'})}catch(e){setError(e instanceof Error?e.message:'Failed to create team');toast({title:'Could not create team',description:e instanceof Error?e.message:undefined,variant:'destructive'})}finally{setSaving(false)}}
 const updateTeam=async()=>{if(!editing||!companyId)return;const name=editing.name.trim();const description=editing.description?.trim()||null;if(!name){toast({title:'Team name required',variant:'destructive'});return}setSaving(true);try{const teamPayload={name,description};const {error}=await supabase.from('teams').update(teamPayload).eq('id',editing.id).eq('company_id',companyId);if(error)throw error;setEditOpen(false);await loadTeams();toast({title:'Team updated'})}catch(e){toast({title:'Could not update team',description:e instanceof Error?e.message:undefined,variant:'destructive'})}finally{setSaving(false)}}
 const deleteTeam=async()=>{if(!deleting||!companyId)return;setSaving(true);try{const {error}=await supabase.from('teams').delete().eq('id',deleting.id).eq('company_id',companyId);if(error)throw error;if(selected===deleting.id){setSelected(null);setMobileList(true)}setDeleteOpen(false);await loadTeams();toast({title:'Team deleted'})}catch(e){toast({title:'Could not delete team',description:e instanceof Error?e.message:undefined,variant:'destructive'})}finally{setSaving(false)}}
 return <div className="flex h-[calc(100vh-160px)] min-h-[520px] w-full overflow-hidden rounded-2xl border border-border bg-muted/30 shadow-sm">
  <aside className={`${mobileList?'translate-x-0':'-translate-x-full'} absolute inset-y-0 left-0 z-30 flex w-full flex-col border-r bg-background transition-transform md:static md:w-[340px] md:translate-x-0 lg:w-[380px]`}>
   <div className="border-b bg-background px-5 pb-4 pt-6"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Workspace</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Teams</h1><p className="mt-1 text-sm text-muted-foreground">Stay connected with your people.</p></div><Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogTrigger asChild><Button size="icon" className="rounded-full" aria-label="Create team"><Plus /></Button></DialogTrigger><DialogContent className="max-w-lg overflow-hidden p-0"><DialogHeader className="border-b border-border bg-card px-6 py-5 text-left"><DialogTitle className="text-lg font-semibold">Create team</DialogTitle><DialogDescription className="mt-1 text-sm text-muted-foreground">Create a collaboration space for your team.</DialogDescription></DialogHeader><div className="space-y-5 bg-card px-6 py-6"><div className="space-y-2"><Label htmlFor="team-name">Team name</Label><Input id="team-name" autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. IT Support"/></div><div className="space-y-2"><Label htmlFor="team-description">Description <span className="font-normal text-muted-foreground">(optional)</span></Label><Textarea id="team-description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="What does this team handle?"/></div>{error&&<p className="rounded-lg bg-destructive/10 px-3 py-2 text-sm text-destructive">{error}</p>}</div><DialogFooter className="border-t border-border bg-muted/20 px-6 py-4"><Button type="button" variant="outline" onClick={()=>setCreateOpen(false)}>Cancel</Button><Button disabled={saving} onClick={createTeam}>{saving?<Loader2 className="animate-spin"/>:<Plus/>}{saving?'Creating…':'Create team'}</Button></DialogFooter></DialogContent></Dialog></div><div className="relative mt-5"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={17}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search conversations" className="h-11 rounded-xl border-0 bg-muted pl-10"/></div></div>
   <div className="flex items-center justify-between px-5 py-3 text-xs font-medium text-muted-foreground"><span>{visible.length} conversation{visible.length===1?'':'s'}</span><span>{visible.reduce((n,t)=>n+t.member_count,0)} members</span></div>
   <div className="flex-1 overflow-y-auto px-2 pb-4">{loading?<div className="grid h-full place-items-center"><Loader size="md"/></div>:error&&visible.length===0?<div className="p-6 text-center"><AlertCircle className="mx-auto mb-2 text-destructive"/><p className="text-sm text-muted-foreground">{error}</p></div>:visible.length===0?<div className="p-8 text-center"><Users className="mx-auto mb-3 text-muted-foreground"/><p className="font-medium">No teams found</p><p className="mt-1 text-sm text-muted-foreground">Create a team or adjust your search.</p></div>:visible.map((t,i)=><div key={t.id} className="group relative"><button onClick={()=>{setSelected(t.id);setMobileList(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left transition ${selected===t.id?'bg-primary/10':'hover:bg-muted/70'}`}><Avatar className="size-12 shrink-0"><AvatarFallback className={`bg-gradient-to-br ${t.avatar_color||colors[i%colors.length]} font-semibold text-white`}>{initials(t.name)}</AvatarFallback></Avatar><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className="truncate font-semibold">{t.name}</span>{t.user_role==='lead'&&<Badge variant="secondary" className="px-1.5 py-0 text-[10px]">Lead</Badge>}</span><span className="mt-1 block truncate text-sm text-muted-foreground">{t.description||`${t.member_count} members`}</span></span><span className="text-xs text-muted-foreground">{t.member_count}</span></button>{t.user_role==='lead'&&<div className="absolute right-2 top-1/2 hidden -translate-y-1/2 gap-1 rounded-lg bg-background shadow-sm group-hover:flex"><Button variant="ghost" size="icon" aria-label={`Edit ${t.name}`} onClick={()=>{setEditing({...t});setEditOpen(true)}}><Edit2/></Button><Button variant="ghost" size="icon" aria-label={`Delete ${t.name}`} onClick={()=>{setDeleting(t);setDeleteOpen(true)}}><Trash2 className="text-destructive"/></Button></div>}</div>)}</div>
  </aside>
  <main className={`${mobileList?'hidden md:flex':'flex'} min-w-0 flex-1 flex-col`}>{selectedTeam?<TeamChatView teamId={selectedTeam.id} onClose={()=>setMobileList(true)}/>:<div className="m-auto max-w-sm px-8 text-center"><div className="mx-auto mb-5 grid size-20 place-items-center rounded-3xl bg-primary/10 text-primary"><MessageSquare size={32}/></div><h2 className="text-2xl font-bold">Your team conversations</h2><p className="mt-2 text-muted-foreground">Choose a team from the list to start chatting.</p></div>}</main>
  <Button onClick={()=>navigate('/app/dashboard')} size="icon" className="fixed bottom-5 right-5 rounded-full shadow-xl md:hidden" aria-label="Go to dashboard"><Home/></Button>
  <Dialog open={editOpen} onOpenChange={setEditOpen}><DialogContent className="max-w-lg overflow-hidden p-0"><DialogHeader className="border-b border-border bg-card px-6 py-5 text-left"><DialogTitle className="text-lg font-semibold">Edit team</DialogTitle><DialogDescription className="mt-1 text-sm text-muted-foreground">Update the team's name and description.</DialogDescription></DialogHeader>{editing&&<div className="space-y-5 bg-card px-6 py-6"><div className="space-y-2"><Label htmlFor="edit-team-name">Team name</Label><Input id="edit-team-name" value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></div><div className="space-y-2"><Label htmlFor="edit-team-description">Description <span className="font-normal text-muted-foreground">(optional)</span></Label><Textarea id="edit-team-description" value={editing.description??''} onChange={e=>setEditing({...editing,description:e.target.value})}/></div></div>}<DialogFooter className="border-t border-border bg-muted/20 px-6 py-4"><Button type="button" variant="outline" onClick={()=>setEditOpen(false)}>Cancel</Button><Button onClick={updateTeam} disabled={saving}>{saving?<Loader2 className="animate-spin"/>:'Save changes'}</Button></DialogFooter></DialogContent></Dialog><AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete team?</AlertDialogTitle><AlertDialogDescription>This permanently removes the team and its messages.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={saving} onClick={deleteTeam}>Delete team</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}
