import { useEffect, useState } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { useTickets } from '@/hooks/useTickets'
import { TicketList } from '@/components/Ticket/TicketList'
import { TicketForm } from '@/components/Ticket/TicketForm'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Dialog, DialogContent } from '@/components/ui/dialog'
import { AlertCircle, CheckCircle2, Clock3, Download, Filter, Plus, Search, Loader2 } from 'lucide-react'
import { useAuth } from '@/lib/auth'
import { useToast } from '@/hooks/use-toast'

export default function TicketsPage({newTicket=false}:{newTicket?:boolean}){
 const navigate=useNavigate();const location=useLocation();const{user}=useAuth();const{toast}=useToast();const{tickets,loading,fetchTickets,loadNextPage,hasMore}=useTickets();const[tab,setTab]=useState<'incoming'|'outgoing'>('incoming');const[search,setSearch]=useState('');const[status,setStatus]=useState('all');const[priority,setPriority]=useState('all');const[openForm,setOpenForm]=useState(newTicket||location.pathname==='/app/tickets/new')
 useEffect(()=>{const timer=setTimeout(()=>{void fetchTickets({assignedTo:tab==='incoming'?user?.id:undefined,createdBy:tab==='outgoing'?user?.id:undefined,status:status==='all'?undefined:status as any,priority:priority==='all'?undefined:priority as any,search:search.trim()||undefined},{showLoading:true})},250);return()=>clearTimeout(timer)},[tab,status,priority,search,user?.id])
 const exportCsv=()=>{if(!tickets.length){toast({title:'Nothing to export',description:'No tickets match the current server-side filters.'});return}const headers=['Ticket','Subject','Status','Priority','Requester','Assignee','Created'];const lines=tickets.map(t=>[t.ticket_number,t.subject,t.status,t.priority,t.requester?.full_name,t.assignee?.full_name,t.created_at].map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(','));const blob=new Blob([[headers.join(','),...lines].join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`desk-support-tickets-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
 const close=()=>{setOpenForm(false);if(location.pathname==='/app/tickets/new')navigate('/app/tickets')};const created=(id:string)=>{close();navigate(`/app/tickets/${id}`)}
 const open=tickets.filter(t=>t.status==='open').length;const progress=tickets.filter(t=>t.status==='in_progress').length;const resolved=tickets.filter(t=>t.status==='resolved'||t.status==='closed').length
 return <div className="space-y-6"><div className="flex justify-end gap-2"><Button variant="outline" onClick={exportCsv}><Download className="mr-2 h-4 w-4"/>Export current page</Button><Button onClick={()=>setOpenForm(true)}><Plus className="mr-2 h-4 w-4"/>New ticket</Button></div><div className="grid grid-cols-3 gap-3"><Card className="p-4"><p className="text-xs text-muted-foreground">Open</p><p className="mt-1 text-xl font-semibold">{open}</p></Card><Card className="p-4"><p className="text-xs text-muted-foreground">In progress</p><p className="mt-1 text-xl font-semibold">{progress}</p></Card><Card className="p-4"><p className="text-xs text-muted-foreground">Resolved</p><p className="mt-1 text-xl font-semibold">{resolved}</p></Card></div><Card className="overflow-hidden"><div className="border-b p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="inline-flex rounded-lg border p-1"><button className={`rounded px-3 py-1.5 text-xs ${tab==='incoming'?'bg-muted font-medium':''}`} onClick={()=>setTab('incoming')}>Assigned to me</button><button className={`rounded px-3 py-1.5 text-xs ${tab==='outgoing'?'bg-muted font-medium':''}`} onClick={()=>setTab('outgoing')}>Created by me</button></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="w-[260px] pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tickets"/></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-[135px]"><Filter className="mr-2 h-4 w-4"/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All status</SelectItem><SelectItem value="open">Open</SelectItem><SelectItem value="in_progress">In progress</SelectItem><SelectItem value="pending">Pending</SelectItem><SelectItem value="resolved">Resolved</SelectItem><SelectItem value="closed">Closed</SelectItem></SelectContent></Select><Select value={priority} onValueChange={setPriority}><SelectTrigger className="w-[135px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All priority</SelectItem><SelectItem value="low">Low</SelectItem><SelectItem value="medium">Medium</SelectItem><SelectItem value="high">High</SelectItem><SelectItem value="urgent">Urgent</SelectItem></SelectContent></Select></div></div></div><TicketList tickets={tickets} loading={loading} onRowClick={id=>navigate(`/app/tickets/${id}`)}/>{hasMore&&<div className="flex justify-center border-t p-4"><Button variant="outline" disabled={loading} onClick={()=>void loadNextPage()}>{loading?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:null}Load more</Button></div>}</Card><Dialog open={openForm} onOpenChange={setOpenForm}><DialogContent className="max-w-2xl p-0"><TicketForm onSubmit={created}/></DialogContent></Dialog></div>
}
