import * as React from 'react'
import { useNavigate } from 'react-router-dom'
import { Search, Package, Ticket as TicketIcon, Loader2 } from 'lucide-react'
import { CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from './ui/command'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/lib/auth'
type SearchResult={id:string;title:string;subtitle?:string;type:'ticket'|'asset';href:string}
export function SearchCommand(){
 const navigate=useNavigate();const{user}=useAuth();const[open,setOpen]=React.useState(false);const[query,setQuery]=React.useState('');const[results,setResults]=React.useState<SearchResult[]>([]);const[loading,setLoading]=React.useState(false);const requestId=React.useRef(0)
 React.useEffect(()=>{const down=(event:KeyboardEvent)=>{if(event.key.toLowerCase()==='k'&&(event.metaKey||event.ctrlKey)){event.preventDefault();setOpen(value=>!value)}};document.addEventListener('keydown',down);return()=>document.removeEventListener('keydown',down)},[])
 React.useEffect(()=>{if(!open)return;const term=query.trim();const safeTerm=term.replace(/[%_,]/g,' ').replace(/\s+/g,' ').trim();if(!user?.company_id||safeTerm.length<2){setResults([]);setLoading(false);return};const currentRequest=++requestId.current;const timer=window.setTimeout(async()=>{setLoading(true);try{const{data:allowed,error:limitError}=await supabase.rpc('consume_user_rate_limit',{p_scope:'workspace-search',p_limit:60,p_window_seconds:60});if(limitError)throw limitError;if(!allowed)throw new Error('Search rate limit reached. Please wait a moment.');const[{data:ticketData,error:ticketError},{data:assetData,error:assetError}]=await Promise.all([supabase.rpc('search_tickets',{p_company_id:user.company_id,p_cursor_created_at:null,p_cursor_id:null,p_limit:8,p_status:null,p_assignee_id:null,p_asset_id:null,p_team_id:null,p_department_id:null,p_priority:null,p_search:safeTerm,p_archived:false,p_created_by:null} as never),supabase.from('assets').select('id,name,asset_tag,serial_number,manufacturer,model').eq('company_id',user.company_id).is('archived_at',null).or(`name.ilike.%${safeTerm}%,asset_tag.ilike.%${safeTerm}%,serial_number.ilike.%${safeTerm}%,manufacturer.ilike.%${safeTerm}%,model.ilike.%${safeTerm}%`).order('created_at',{ascending:false}).limit(8)]);if(ticketError)throw ticketError;if(assetError)throw assetError;if(currentRequest!==requestId.current)return;const payload=(ticketData??{}) as{items?:Array<Record<string,unknown>>};const tickets=(payload.items??[]).map(ticket=>({id:String(ticket.id),title:String(ticket.title??ticket.subject??'Untitled ticket'),subtitle:ticket.ticket_number?`Ticket ${String(ticket.ticket_number)}`:'Support ticket',type:'ticket' as const,href:`/app/tickets/${String(ticket.id)}`}));const assets=((assetData??[])as Array<Record<string,unknown>>).map(asset=>({id:String(asset.id),title:String(asset.name??'Unnamed asset'),subtitle:asset.asset_tag?`Asset ${String(asset.asset_tag)}`:'Asset record',type:'asset' as const,href:`/app/assets/${String(asset.id)}`}));setResults([...tickets,...assets])}catch(error){console.error('Global search failed:',error);if(currentRequest===requestId.current)setResults([])}finally{if(currentRequest===requestId.current)setLoading(false)}},220);return()=>window.clearTimeout(timer)},[open,query,user?.company_id])
 const selectResult=(result:SearchResult)=>{navigate(result.href);setOpen(false);setQuery('')}
 return <><div className="relative w-full"><Search className="pointer-events-none absolute left-3 top-1/2 z-10 h-4 w-4 -translate-y-1/2 text-muted-foreground" aria-hidden="true"/><input value={query} onChange={event=>{setQuery(event.target.value);setOpen(true)}} onFocus={()=>setOpen(true)} placeholder="Search workspace" aria-label="Search workspace" className="h-9 w-full rounded-lg border border-border bg-muted/40 pl-9 pr-12 text-sm text-foreground outline-none transition-colors placeholder:text-muted-foreground focus:border-primary/40 focus:bg-background focus:ring-2 focus:ring-primary/10 sm:h-10"/><kbd className="pointer-events-none absolute right-2 top-1/2 hidden -translate-y-1/2 rounded border border-border bg-background px-1.5 py-0.5 font-mono text-[10px] text-muted-foreground sm:inline-flex" aria-hidden="true">⌘K</kbd></div><CommandDialog open={open} onOpenChange={setOpen}><CommandInput value={query} onValueChange={setQuery} placeholder="Search tickets and assets..." aria-label="Search tickets and assets"/><CommandList>{loading&&<div className="flex items-center justify-center gap-2 py-8 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" aria-hidden="true"/>Searching workspace…</div>}{!loading&&query.trim().length<2&&<div className="py-8 text-center text-sm text-muted-foreground">Type at least 2 characters to search.</div>}{!loading&&query.trim().length>=2&&results.length===0&&<CommandEmpty>No matching tickets or assets.</CommandEmpty>}{results.some(result=>result.type==='ticket')&&<CommandGroup heading="Tickets">{results.filter(result=>result.type==='ticket').map(result=><CommandItem key={`ticket-${result.id}`} value={`${result.title} ${result.subtitle??''}`} onSelect={()=>selectResult(result)}><TicketIcon className="mr-2 h-4 w-4 shrink-0" aria-hidden="true"/><span className="min-w-0"><span className="block truncate">{result.title}</span><span className="block truncate text-xs text-muted-foreground">{result.subtitle}</span></span></CommandItem>)}</CommandGroup>}{results.some(result=>result.type==='asset')&&<CommandGroup heading="Assets">{results.filter(result=>result.type==='asset').map(result=><CommandItem key={`asset-${result.id}`} value={`${result.title} ${result.subtitle??''}`} onSelect={()=>selectResult(result)}><Package className="mr-2 h-4 w-4 shrink-0" aria-hidden="true"/><span className="min-w-0"><span className="block truncate">{result.title}</span><span className="block truncate text-xs text-muted-foreground">{result.subtitle}</span></span></CommandItem>)}</CommandGroup>}</CommandList></CommandDialog></>
}
