// App.tsx - canonical application routing
import React from 'react'
import { HashRouter, Routes, Route, Navigate, Outlet, useLocation } from 'react-router-dom'
import { AuthProvider, useAuth } from './lib/auth'
import { ErrorBoundary } from './components/ErrorBoundary'
import { Toaster } from 'react-hot-toast'
import { NotificationProvider, useNotifications } from './context/NotificationContext'
import { QRCodeProvider } from './context/QRCodeContext'
import { ThemeProvider } from './context/ThemeContext'
import { ColorSchemeProvider } from './context/ColorSchemeContext'
import { ToastContainer } from '@/components/ToastNotification'
import LandingPage from './pages/LandingPage';import LoginPage from './pages/LoginPage';import DashboardPage from './pages/DashboardPage';import TicketsPage from './pages/TicketsPage';import TicketDetailPage from '@/pages/tickets/[id]';import TicketSettingsPage from './pages/TicketSettingsPage';import AssetsPage from './pages/AssetsPage';import AssetDetailPage from '@/pages/assets/[id]';import ProfilePage from './pages/ProfilePage';import UsersPage from './pages/UsersPage';import UserDetailPage from '@/pages/users/[id]';import DepartmentsPage from './pages/DepartmentsPage';import DepartmentDetailPage from './pages/departments/[id]';import TeamsPage from './pages/TeamsPage';import CallPage from './pages/CallPage';import CommunicationsPage from './pages/CommunicationsPage';import AuditPage from './pages/AuditPage';import SettingsPage from './pages/SettingsPage';import QRScannerPage from './pages/QRScannerPage';import WorkspacePage from './pages/WorkspacePage';import NotificationsPage from './pages/NotificationsPage';import Layout from './components/layout/Layout'
function LoadingRoute(){return <div className="grid min-h-screen place-items-center text-sm text-muted-foreground">Loading…</div>}
function ProtectedLayout(){const {user,loading}=useAuth();const location=useLocation();if(loading)return <LoadingRoute/>;if(!user)return <Navigate to="/login" state={{from:location}} replace/>;return <Layout><Outlet/></Layout>}
function AdminOrHRLayout(){const {user,loading}=useAuth();if(loading)return <LoadingRoute/>;if(!user||(user.role!=='admin'&&user.role!=='hr'))return <Navigate to="/app/dashboard" replace/>;return <Layout><Outlet/></Layout>}
function ServiceDeskConfigLayout(){const {user,loading}=useAuth();if(loading)return <LoadingRoute/>;if(!user||!['admin','hr','manager'].includes(user.role??''))return <Navigate to="/app/dashboard" replace/>;return <Layout><Outlet/></Layout>}
function AuditLayout(){const {user,loading}=useAuth();if(loading)return <LoadingRoute/>;if(!user||!['admin','hr','manager'].includes(user.role??''))return <Navigate to="/app/dashboard" replace/>;return <Layout><Outlet/></Layout>}
function AppRoutes(){const {user}=useAuth();return <Routes><Route path="/" element={user?<Navigate to="/app/dashboard" replace/>:<LandingPage/>}/><Route path="/login" element={user?<Navigate to="/app/dashboard" replace/>:<LoginPage defaultToSignUp={false}/>}/><Route path="/signup" element={user?<Navigate to="/app/dashboard" replace/>:<LoginPage defaultToSignUp/>}/><Route path="/app" element={<ProtectedLayout/>}><Route index element={<Navigate to="dashboard" replace/>}/><Route path="dashboard" element={<DashboardPage/>}/><Route path="dashboard/users" element={<Navigate to="../users" replace/>}/><Route path="dashboard/assets" element={<Navigate to="../assets" replace/>}/><Route path="tickets" element={<TicketsPage/>}/><Route path="tickets/new" element={<TicketsPage newTicket/>}/><Route path="tickets/:id" element={<TicketDetailPage/>}/><Route path="assets" element={<AssetsPage/>}/><Route path="assets/new" element={<AssetsPage/>}/><Route path="assets/:id" element={<AssetDetailPage/>}/><Route path="departments" element={<DepartmentsPage/>}/><Route path="departments/:id" element={<DepartmentDetailPage/>}/><Route path="teams" element={<TeamsPage/>}/><Route path="teams/call/:roomId" element={<CallPage/>}/><Route path="communications" element={<CommunicationsPage/>}/><Route path="calls/:callId" element={<CallPage/>}/><Route path="settings" element={<SettingsPage/>}/><Route path="profile" element={<ProfilePage/>}/><Route path="qr-scanner" element={<QRScannerPage/>}/><Route path="working-area" element={<WorkspacePage/>}/><Route path="workspace" element={<WorkspacePage/>}/><Route path="notifications" element={<NotificationsPage/>}/></Route><Route path="/app/audit" element={<AuditLayout/>}><Route index element={<AuditPage/>}/></Route><Route path="/app/ticket-settings" element={<ServiceDeskConfigLayout/>}><Route index element={<TicketSettingsPage/>}/></Route><Route path="/app/users" element={<AdminOrHRLayout/>}><Route index element={<UsersPage/>}/><Route path=":id" element={<UserDetailPage/>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
function ToastWrapper(){const location=useLocation();const {toasts,dismissToast,setCurrentPath}=useNotifications();React.useEffect(()=>{setCurrentPath(window.location.hash.replace('#','')||location.pathname)},[location.pathname,setCurrentPath]);return <ToastContainer toasts={toasts} onDismiss={dismissToast}/>}
export default function App(){return <ErrorBoundary><AuthProvider><ThemeProvider><ColorSchemeProvider><NotificationProvider><QRCodeProvider><HashRouter><ToastWrapper/><AppRoutes/><Toaster position="bottom-right" toastOptions={{duration:5000}}/></HashRouter></QRCodeProvider></NotificationProvider></ColorSchemeProvider></ThemeProvider></AuthProvider></ErrorBoundary>}
