drop policy if exists tickets_update_manager on public.tickets;
drop policy if exists tickets_update_requester on public.tickets;
drop policy if exists ticket_sla_manage_admin on public.ticket_sla_policies;
create policy ticket_sla_insert_manager on public.ticket_sla_policies for insert to authenticated with check(private.has_company_role(company_id,array['admin'::membership_role,'hr'::membership_role,'manager'::membership_role]));
create policy ticket_sla_update_manager on public.ticket_sla_policies for update to authenticated using(private.has_company_role(company_id,array['admin'::membership_role,'hr'::membership_role,'manager'::membership_role])) with check(private.has_company_role(company_id,array['admin'::membership_role,'hr'::membership_role,'manager'::membership_role]));
create policy ticket_sla_delete_manager on public.ticket_sla_policies for delete to authenticated using(private.has_company_role(company_id,array['admin'::membership_role,'hr'::membership_role,'manager'::membership_role]));
create policy tickets_update_authorized on public.tickets for update to authenticated using(private.can_manage_ticket(id) or (requester_id=auth.uid() and status not in ('resolved','closed'))) with check(company_id=any(current_company_id_array()));
drop index if exists public.idx_tickets_company_due_at;drop index if exists public.idx_tickets_due_at;drop index if exists public.idx_tickets_open_queue;
create index if not exists idx_tickets_accepted_by on public.tickets(accepted_by) where accepted_by is not null;
create index if not exists idx_tickets_created_by on public.tickets(created_by,created_at desc);
create index if not exists idx_tickets_category_company on public.tickets(company_id,category_id);
create index if not exists idx_tickets_department on public.tickets(department_id) where department_id is not null;
create index if not exists idx_tickets_team on public.tickets(team_id) where team_id is not null;
create index if not exists idx_tickets_sla_policy on public.tickets(sla_policy_id) where sla_policy_id is not null;
create index if not exists idx_ticket_assignments_department on public.ticket_assignments(department_id) where department_id is not null;
create index if not exists idx_ticket_assignments_team on public.ticket_assignments(team_id) where team_id is not null;
create index if not exists idx_ticket_attachments_comment on public.ticket_attachments(comment_id) where comment_id is not null;
create index if not exists idx_ticket_categories_department on public.ticket_categories(department_id) where department_id is not null;
create index if not exists idx_ticket_categories_team on public.ticket_categories(team_id) where team_id is not null;
create index if not exists idx_ticket_escalations_actor on public.ticket_escalations(escalated_by,created_at desc);
create index if not exists idx_ticket_watchers_added_by on public.ticket_watchers(added_by,created_at desc);
