create or replace function private.record_asset_status_change() returns trigger language plpgsql security definer set search_path=public,pg_catalog as $$ begin if tg_op='UPDATE' and new.status is distinct from old.status then insert into public.asset_history(asset_id,actor_id,event_type,description,previous_status,new_status,metadata) values(new.id,auth.uid(),'status_changed','Asset status changed from '||old.status::text||' to '||new.status::text,old.status,new.status,'{}'::jsonb); end if; return new; end; $$;
revoke all on function private.record_asset_status_change() from public;
drop trigger if exists trg_asset_status_history on public.assets;
create trigger trg_asset_status_history after update of status on public.assets for each row execute function private.record_asset_status_change();

create or replace function private.sync_asset_assignment_state() returns trigger language plpgsql security definer set search_path=public,pg_catalog as $$ begin if tg_op='INSERT' then update public.assets set status='assigned' where id=new.asset_id and status not in ('retired','lost','maintenance'); insert into public.asset_history(asset_id,actor_id,event_type,description,metadata) values(new.asset_id,new.assigned_by,'assigned','Asset assigned to user',jsonb_build_object('assignment_id',new.id)); return new; elsif tg_op='UPDATE' and old.returned_at is null and new.returned_at is not null then update public.assets set status='active' where id=new.asset_id and status='assigned' and not exists(select 1 from public.asset_assignments aa where aa.asset_id=new.asset_id and aa.returned_at is null and aa.id<>new.id); insert into public.asset_history(asset_id,actor_id,event_type,description,metadata) values(new.asset_id,coalesce(auth.uid(),new.assigned_by),'returned','Asset returned from assignment',jsonb_build_object('assignment_id',new.id)); return new; end if; return new; end; $$;
revoke all on function private.sync_asset_assignment_state() from public;
drop trigger if exists trg_asset_assignment_state on public.asset_assignments;
create trigger trg_asset_assignment_state after insert or update of returned_at on public.asset_assignments for each row execute function private.sync_asset_assignment_state();

create or replace function private.prevent_invalid_asset_assignment() returns trigger language plpgsql security definer set search_path=public,pg_catalog as $$ declare v_company uuid; begin select company_id into v_company from public.assets where id=new.asset_id; if v_company is null then raise exception 'Asset not found'; end if; if not exists(select 1 from public.company_memberships m where m.company_id=v_company and m.user_id=new.assigned_to and m.is_active=true) then raise exception 'Assigned user is not an active member of the asset company'; end if; if exists(select 1 from public.asset_assignments aa where aa.asset_id=new.asset_id and aa.returned_at is null and aa.id<>coalesce(new.id,'00000000-0000-0000-0000-000000000000'::uuid)) then raise exception 'Asset already has an active assignment'; end if; return new; end; $$;
revoke all on function private.prevent_invalid_asset_assignment() from public;
drop trigger if exists trg_asset_assignment_validation on public.asset_assignments;
create trigger trg_asset_assignment_validation before insert or update on public.asset_assignments for each row execute function private.prevent_invalid_asset_assignment();
