-- Persistent WhatsApp/Telegram-style communication model.
-- Media is never transported through Postgres; Supabase Realtime Broadcast is used only for WebRTC signaling.
create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade,
  kind text not null default 'direct' check(kind in ('direct','group','team','ticket')), title text, avatar_path text,
  created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check(role in ('owner','admin','member')), joined_at timestamptz not null default now(),
  last_read_at timestamptz, muted_until timestamptz, archived_at timestamptz, primary key(conversation_id,user_id)
);
create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id), message_type text not null default 'text' check(message_type in ('text','image','video','audio','voice','file','system','call')),
  body text, reply_to_id uuid references public.messages(id) on delete set null, metadata jsonb not null default '{}'::jsonb,
  edited_at timestamptz, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint messages_content_check check(message_type in ('system','call') or body is not null or deleted_at is not null)
);
create table if not exists public.message_attachments (
  id uuid primary key default gen_random_uuid(), message_id uuid not null references public.messages(id) on delete cascade,
  storage_path text not null, file_name text not null, mime_type text not null, file_size_bytes bigint not null check(file_size_bytes between 1 and 52428800),
  width integer, height integer, duration_seconds integer, created_at timestamptz not null default now(), unique(message_id,storage_path)
);
create table if not exists public.conversation_message_reactions (
  message_id uuid not null references public.messages(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade,
  reaction text not null check(char_length(trim(reaction)) between 1 and 16), created_at timestamptz not null default now(), primary key(message_id,user_id,reaction)
);
create table if not exists public.message_read_receipts (
  message_id uuid not null references public.messages(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(), primary key(message_id,user_id)
);
create table if not exists public.calls (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade,
  conversation_id uuid references public.conversations(id) on delete set null, initiator_id uuid not null references public.profiles(id),
  call_type text not null default 'video' check(call_type in ('audio','video')),
  status text not null default 'initiating' check(status in ('initiating','ringing','connecting','connected','ended','declined','missed','failed','disconnected')),
  started_at timestamptz, connected_at timestamptz, ended_at timestamptz, end_reason text, metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.call_participants_v2 (
  call_id uuid not null references public.calls(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'participant' check(role in ('initiator','participant')),
  status text not null default 'invited' check(status in ('invited','ringing','connecting','connected','declined','missed','joined','left')),
  joined_at timestamptz, left_at timestamptz, created_at timestamptz not null default now(), primary key(call_id,user_id)
);
create index if not exists conversations_company_updated_idx on public.conversations(company_id,updated_at desc);
create index if not exists conversation_members_user_idx on public.conversation_members(user_id,conversation_id);
create index if not exists messages_conversation_created_idx on public.messages(conversation_id,created_at desc);
create index if not exists messages_sender_idx on public.messages(sender_id,created_at desc);
create index if not exists messages_reply_to_idx on public.messages(reply_to_id);
create index if not exists message_attachments_message_idx on public.message_attachments(message_id);
create index if not exists conversation_reactions_user_idx on public.conversation_message_reactions(user_id);
create index if not exists message_read_receipts_user_idx on public.message_read_receipts(user_id);
create index if not exists calls_company_idx on public.calls(company_id);
create index if not exists calls_conversation_created_idx on public.calls(conversation_id,created_at desc);
create index if not exists calls_initiator_created_idx on public.calls(initiator_id,created_at desc);
create index if not exists call_participants_v2_user_idx on public.call_participants_v2(user_id,created_at desc);
create or replace function private.is_company_member(p_company_id uuid,p_user_id uuid) returns boolean language sql stable security invoker set search_path=public,private as $$ select exists(select 1 from public.company_memberships where company_id=p_company_id and user_id=p_user_id and is_active); $$;
create or replace function private.is_conversation_member(p_conversation_id uuid,p_user_id uuid) returns boolean language sql stable security invoker set search_path=public,private as $$ select exists(select 1 from public.conversation_members m join public.conversations c on c.id=m.conversation_id where m.conversation_id=p_conversation_id and m.user_id=p_user_id and private.is_company_member(c.company_id,p_user_id)); $$;
create or replace function private.can_manage_conversation(p_conversation_id uuid,p_user_id uuid) returns boolean language sql stable security invoker set search_path=public,private as $$ select exists(select 1 from public.conversation_members where conversation_id=p_conversation_id and user_id=p_user_id and role in('owner','admin')); $$;
create or replace function public.create_direct_conversation(p_other_user_id uuid) returns uuid language plpgsql security invoker set search_path=public,private as $$ declare v_me uuid:=auth.uid();v_company uuid;v_id uuid; begin if v_me is null or p_other_user_id is null or v_me=p_other_user_id then raise exception 'Invalid participants'; end if; select company_id into v_company from public.company_memberships where user_id=v_me and is_active order by created_at limit 1; if v_company is null or not private.is_company_member(v_company,p_other_user_id) then raise exception 'Users are not active members of the same company'; end if; select c.id into v_id from public.conversations c where c.company_id=v_company and c.kind='direct' and exists(select 1 from public.conversation_members where conversation_id=c.id and user_id=v_me) and exists(select 1 from public.conversation_members where conversation_id=c.id and user_id=p_other_user_id) limit 1; if v_id is not null then return v_id; end if; insert into public.conversations(company_id,kind,created_by) values(v_company,'direct',v_me) returning id into v_id; insert into public.conversation_members values(v_id,v_me,'owner',now(),null,null,null),(v_id,p_other_user_id,'member',now(),null,null,null); return v_id; end; $$;
create or replace function public.start_call(p_conversation_id uuid,p_call_type text default 'video') returns uuid language plpgsql security invoker set search_path=public,private as $$ declare v_me uuid:=auth.uid();v_company uuid;v_call uuid;v_count int; begin if v_me is null or p_call_type not in('audio','video') or not private.is_conversation_member(p_conversation_id,v_me) then raise exception 'Not authorized'; end if; select company_id into v_company from public.conversations where id=p_conversation_id; insert into public.calls(company_id,conversation_id,initiator_id,call_type,status,started_at) values(v_company,p_conversation_id,v_me,p_call_type,'ringing',now()) returning id into v_call; insert into public.call_participants_v2(call_id,user_id,role,status) select v_call,user_id,case when user_id=v_me then 'initiator' else 'participant' end,case when user_id=v_me then 'connected' else 'ringing' end from public.conversation_members where conversation_id=p_conversation_id; select count(*) into v_count from public.call_participants_v2 where call_id=v_call; if v_count=1 then update public.calls set status='connected',connected_at=now() where id=v_call; end if; return v_call; end; $$;
create or replace function public.update_call_status(p_call_id uuid,p_status text,p_reason text default null) returns void language plpgsql security invoker set search_path=public,private as $$ declare v_me uuid:=auth.uid(); begin if p_status not in('initiating','ringing','connecting','connected','ended','declined','missed','failed','disconnected') then raise exception 'Invalid call status'; end if; if not exists(select 1 from public.call_participants_v2 where call_id=p_call_id and user_id=v_me) then raise exception 'Not a call participant'; end if; update public.calls set status=p_status,end_reason=coalesce(p_reason,end_reason),started_at=case when p_status in('connecting','connected') then coalesce(started_at,now()) else started_at end,connected_at=case when p_status='connected' then coalesce(connected_at,now()) else connected_at end,ended_at=case when p_status in('ended','declined','missed','failed','disconnected') then coalesce(ended_at,now()) else ended_at end,updated_at=now() where id=p_call_id; update public.call_participants_v2 set status=case when p_status='connected' then 'joined' when p_status='declined' then 'declined' when p_status='missed' then 'missed' when p_status in('ended','disconnected','failed') then 'left' else status end,joined_at=case when p_status='connected' then coalesce(joined_at,now()) else joined_at end,left_at=case when p_status in('ended','disconnected','failed','declined','missed') then coalesce(left_at,now()) else left_at end where call_id=p_call_id and user_id=v_me; end; $$;

alter table public.conversations enable row level security; alter table public.conversation_members enable row level security; alter table public.messages enable row level security; alter table public.message_attachments enable row level security; alter table public.conversation_message_reactions enable row level security; alter table public.message_read_receipts enable row level security; alter table public.calls enable row level security; alter table public.call_participants_v2 enable row level security;
create policy conversations_select on public.conversations for select to authenticated using(private.is_conversation_member(id,(select auth.uid()))); create policy conversations_insert on public.conversations for insert to authenticated with check(created_by=(select auth.uid()) and private.is_company_member(company_id,(select auth.uid()))); create policy conversations_update on public.conversations for update to authenticated using(private.can_manage_conversation(id,(select auth.uid()))) with check(private.can_manage_conversation(id,(select auth.uid())));
create policy conversation_members_select on public.conversation_members for select to authenticated using(private.is_conversation_member(conversation_id,(select auth.uid()))); create policy conversation_members_insert on public.conversation_members for insert to authenticated with check(private.can_manage_conversation(conversation_id,(select auth.uid())) and private.is_company_member((select company_id from public.conversations where id=conversation_id),user_id)); create policy conversation_members_update on public.conversation_members for update to authenticated using(user_id=(select auth.uid()) or private.can_manage_conversation(conversation_id,(select auth.uid()))) with check(user_id=(select auth.uid()) or private.can_manage_conversation(conversation_id,(select auth.uid()))); create policy conversation_members_delete on public.conversation_members for delete to authenticated using(user_id=(select auth.uid()) or private.can_manage_conversation(conversation_id,(select auth.uid())));
create policy messages_select on public.messages for select to authenticated using(private.is_conversation_member(conversation_id,(select auth.uid()))); create policy messages_insert on public.messages for insert to authenticated with check(sender_id=(select auth.uid()) and private.is_conversation_member(conversation_id,(select auth.uid()))); create policy messages_update on public.messages for update to authenticated using(sender_id=(select auth.uid()) and private.is_conversation_member(conversation_id,(select auth.uid()))) with check(sender_id=(select auth.uid()) and private.is_conversation_member(conversation_id,(select auth.uid()))); create policy messages_delete on public.messages for delete to authenticated using(sender_id=(select auth.uid()) and private.is_conversation_member(conversation_id,(select auth.uid())));
create policy attachments_select on public.message_attachments for select to authenticated using(exists(select 1 from public.messages m where m.id=message_id and private.is_conversation_member(m.conversation_id,(select auth.uid())))); create policy attachments_insert on public.message_attachments for insert to authenticated with check(exists(select 1 from public.messages m where m.id=message_id and m.sender_id=(select auth.uid()) and private.is_conversation_member(m.conversation_id,(select auth.uid())))); create policy attachments_delete on public.message_attachments for delete to authenticated using(exists(select 1 from public.messages m where m.id=message_id and m.sender_id=(select auth.uid())));
create policy reactions_select on public.conversation_message_reactions for select to authenticated using(exists(select 1 from public.messages m where m.id=message_id and private.is_conversation_member(m.conversation_id,(select auth.uid())))); create policy reactions_insert on public.conversation_message_reactions for insert to authenticated with check(user_id=(select auth.uid()) and exists(select 1 from public.messages m where m.id=message_id and private.is_conversation_member(m.conversation_id,(select auth.uid())))); create policy reactions_delete on public.conversation_message_reactions for delete to authenticated using(user_id=(select auth.uid()));
create policy receipts_select on public.message_read_receipts for select to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.messages m where m.id=message_id and private.is_conversation_member(m.conversation_id,(select auth.uid())))); create policy receipts_insert on public.message_read_receipts for insert to authenticated with check(user_id=(select auth.uid()) and exists(select 1 from public.messages m where m.id=message_id and private.is_conversation_member(m.conversation_id,(select auth.uid())))); create policy receipts_update on public.message_read_receipts for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy calls_select on public.calls for select to authenticated using(exists(select 1 from public.call_participants_v2 p where p.call_id=id and p.user_id=(select auth.uid()))); create policy calls_update on public.calls for update to authenticated using(exists(select 1 from public.call_participants_v2 p where p.call_id=id and p.user_id=(select auth.uid()))) with check(exists(select 1 from public.call_participants_v2 p where p.call_id=id and p.user_id=(select auth.uid())));
create policy call_participants_select on public.call_participants_v2 for select to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.calls c join public.conversation_members cm on cm.conversation_id=c.conversation_id where c.id=call_id and cm.user_id=(select auth.uid()))); create policy call_participants_update on public.call_participants_v2 for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
revoke all on public.conversations,public.conversation_members,public.messages,public.message_attachments,public.conversation_message_reactions,public.message_read_receipts,public.calls,public.call_participants_v2 from anon; grant select,insert,update,delete on public.conversations,public.conversation_members,public.messages,public.message_attachments,public.conversation_message_reactions,public.message_read_receipts to authenticated; grant select,update on public.calls,public.call_participants_v2 to authenticated; grant execute on function public.create_direct_conversation(uuid),public.start_call(uuid,text),public.update_call_status(uuid,text,text) to authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('message-attachments','message-attachments',false,52428800,array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','audio/mpeg','audio/ogg','audio/webm','application/pdf','text/plain']) on conflict(id) do update set public=false,file_size_limit=52428800,allowed_mime_types=excluded.allowed_mime_types;
create policy message_storage_select on storage.objects for select to authenticated using(bucket_id='message-attachments' and exists(select 1 from public.conversation_members cm where cm.conversation_id=split_part(name,'/',1)::uuid and cm.user_id=(select auth.uid())));
create policy message_storage_insert on storage.objects for insert to authenticated with check(bucket_id='message-attachments' and split_part(name,'/',2)=(select auth.uid())::text and exists(select 1 from public.conversation_members cm where cm.conversation_id=split_part(name,'/',1)::uuid and cm.user_id=(select auth.uid())));
create policy message_storage_delete on storage.objects for delete to authenticated using(bucket_id='message-attachments' and split_part(name,'/',2)=(select auth.uid())::text);
